//go:build go1.22

// Package knowlapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package knowlapi

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"time"

	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Defines values for CitationKind.
const (
	Raw  CitationKind = "raw"
	Wiki CitationKind = "wiki"
)

// Defines values for HealthResponseStatus.
const (
	Ok HealthResponseStatus = "ok"
)

// Defines values for IngestResultStatus.
const (
	IngestResultStatusCompleted IngestResultStatus = "completed"
	IngestResultStatusFailed    IngestResultStatus = "failed"
	IngestResultStatusQueued    IngestResultStatus = "queued"
	IngestResultStatusRunning   IngestResultStatus = "running"
)

// Defines values for OperationResultStatus.
const (
	OperationResultStatusCompleted OperationResultStatus = "completed"
	OperationResultStatusFailed    OperationResultStatus = "failed"
	OperationResultStatusQueued    OperationResultStatus = "queued"
	OperationResultStatusRunning   OperationResultStatus = "running"
)

// Defines values for ReadyResponseStatus.
const (
	NotReady ReadyResponseStatus = "not_ready"
	Ready    ReadyResponseStatus = "ready"
)

// Citation defines model for Citation.
type Citation struct {
	Kind      CitationKind `json:"kind"`
	PageId    *string      `json:"page_id,omitempty"`
	Path      *string      `json:"path,omitempty"`
	Reference string       `json:"reference"`
	SourceRef *string      `json:"source_ref,omitempty"`
	Untrusted bool         `json:"untrusted"`
}

// CitationKind defines model for Citation.Kind.
type CitationKind string

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error string `json:"error"`
}

// EvidenceItem defines model for EvidenceItem.
type EvidenceItem struct {
	PageId     string    `json:"page_id"`
	Snippet    string    `json:"snippet"`
	SourceRefs *[]string `json:"source_refs,omitempty"`
	Title      string    `json:"title"`
	Untrusted  bool      `json:"untrusted"`
}

// Failure defines model for Failure.
type Failure struct {
	Class       string `json:"class"`
	OperationId string `json:"operation_id"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	Service string               `json:"service"`
	Status  HealthResponseStatus `json:"status"`
}

// HealthResponseStatus defines model for HealthResponse.Status.
type HealthResponseStatus string

// IngestRequest defines model for IngestRequest.
type IngestRequest struct {
	// Content Raw source content.
	Content        *string `json:"content,omitempty"`
	IdempotencyKey *string `json:"idempotency_key,omitempty"`
	MediaType      *string `json:"media_type,omitempty"`
	Origin         *string `json:"origin,omitempty"`

	// Uri External source URI.
	Uri *string `json:"uri,omitempty"`
}

// IngestResult defines model for IngestResult.
type IngestResult struct {
	OperationId string             `json:"operation_id"`
	Status      IngestResultStatus `json:"status"`
}

// IngestResultStatus defines model for IngestResult.Status.
type IngestResultStatus string

// OperationResult defines model for OperationResult.
type OperationResult struct {
	Failure   *Failure              `json:"failure,omitempty"`
	Id        string                `json:"id"`
	Status    OperationResultStatus `json:"status"`
	UpdatedAt time.Time             `json:"updated_at"`
}

// OperationResultStatus defines model for OperationResult.Status.
type OperationResultStatus string

// ReadyResponse defines model for ReadyResponse.
type ReadyResponse struct {
	// Scope Trusted scope reported only when the host is ready.
	Scope   *string             `json:"scope,omitempty"`
	Service string              `json:"service"`
	Status  ReadyResponseStatus `json:"status"`
}

// ReadyResponseStatus defines model for ReadyResponse.Status.
type ReadyResponseStatus string

// RetrieveResult defines model for RetrieveResult.
type RetrieveResult struct {
	Citations *[]Citation    `json:"citations,omitempty"`
	Evidence  []EvidenceItem `json:"evidence"`
	Query     string         `json:"query"`
}

// OperationID defines model for OperationID.
type OperationID = string

// RetrieveQuery defines model for RetrieveQuery.
type RetrieveQuery = string

// JSONBodyBadRequest defines model for JSONBodyBadRequest.
type JSONBodyBadRequest = ErrorResponse

// NotFound defines model for NotFound.
type NotFound = ErrorResponse

// OperationFailed defines model for OperationFailed.
type OperationFailed = ErrorResponse

// OperationIDBadRequest defines model for OperationIDBadRequest.
type OperationIDBadRequest = ErrorResponse

// QueryStringBadRequest defines model for QueryStringBadRequest.
type QueryStringBadRequest = ErrorResponse

// ScopeOverrideForbidden defines model for ScopeOverrideForbidden.
type ScopeOverrideForbidden = ErrorResponse

// Unauthorized defines model for Unauthorized.
type Unauthorized = ErrorResponse

// UnavailableError defines model for UnavailableError.
type UnavailableError = ErrorResponse

// RetrieveKnowledgeParams defines parameters for RetrieveKnowledge.
type RetrieveKnowledgeParams struct {
	// Query Free-text retrieval query.
	Query RetrieveQuery `form:"query" json:"query"`
}

// IngestKnowledgeJSONRequestBody defines body for IngestKnowledge for application/json ContentType.
type IngestKnowledgeJSONRequestBody = IngestRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Liveness probe
	// (GET /healthz)
	GetHealth(w http.ResponseWriter, r *http.Request)
	// Readiness probe
	// (GET /readyz)
	GetReady(w http.ResponseWriter, r *http.Request)
	// Submit one bounded source to the trusted Knowl ingest pipeline
	// (POST /v1/ingest)
	IngestKnowledge(w http.ResponseWriter, r *http.Request)
	// Read one durable Knowl operation status
	// (GET /v1/operations/{operation_id})
	GetOperation(w http.ResponseWriter, r *http.Request, operationId OperationID)
	// Retrieve bounded evidence from the trusted Knowl scope
	// (GET /v1/retrieve)
	RetrieveKnowledge(w http.ResponseWriter, r *http.Request, params RetrieveKnowledgeParams)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetReady operation middleware
func (siw *ServerInterfaceWrapper) GetReady(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetReady(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// IngestKnowledge operation middleware
func (siw *ServerInterfaceWrapper) IngestKnowledge(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.IngestKnowledge(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetOperation operation middleware
func (siw *ServerInterfaceWrapper) GetOperation(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "operation_id" -------------
	var operationId OperationID

	err = runtime.BindStyledParameterWithOptions("simple", "operation_id", r.PathValue("operation_id"), &operationId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "operation_id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetOperation(w, r, operationId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RetrieveKnowledge operation middleware
func (siw *ServerInterfaceWrapper) RetrieveKnowledge(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params RetrieveKnowledgeParams

	// ------------- Required query parameter "query" -------------

	if paramValue := r.URL.Query().Get("query"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "query"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "query", r.URL.Query(), &params.Query)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "query", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RetrieveKnowledge(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("GET "+options.BaseURL+"/healthz", wrapper.GetHealth)
	m.HandleFunc("GET "+options.BaseURL+"/readyz", wrapper.GetReady)
	m.HandleFunc("POST "+options.BaseURL+"/v1/ingest", wrapper.IngestKnowledge)
	m.HandleFunc("GET "+options.BaseURL+"/v1/operations/{operation_id}", wrapper.GetOperation)
	m.HandleFunc("GET "+options.BaseURL+"/v1/retrieve", wrapper.RetrieveKnowledge)

	return m
}

type JSONBodyBadRequestJSONResponse ErrorResponse

type NotFoundJSONResponse ErrorResponse

type OperationFailedJSONResponse ErrorResponse

type OperationIDBadRequestJSONResponse ErrorResponse

type QueryStringBadRequestJSONResponse ErrorResponse

type ScopeOverrideForbiddenJSONResponse ErrorResponse

type UnauthorizedResponseHeaders struct {
	WWWAuthenticate string
}
type UnauthorizedJSONResponse struct {
	Body ErrorResponse

	Headers UnauthorizedResponseHeaders
}

type UnavailableErrorJSONResponse ErrorResponse

type GetHealthRequestObject struct {
}

type GetHealthResponseObject interface {
	VisitGetHealthResponse(w http.ResponseWriter) error
}

type GetHealth200JSONResponse HealthResponse

func (response GetHealth200JSONResponse) VisitGetHealthResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetReadyRequestObject struct {
}

type GetReadyResponseObject interface {
	VisitGetReadyResponse(w http.ResponseWriter) error
}

type GetReady200JSONResponse ReadyResponse

func (response GetReady200JSONResponse) VisitGetReadyResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetReady503JSONResponse ReadyResponse

func (response GetReady503JSONResponse) VisitGetReadyResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)

	return json.NewEncoder(w).Encode(response)
}

type IngestKnowledgeRequestObject struct {
	Body *IngestKnowledgeJSONRequestBody
}

type IngestKnowledgeResponseObject interface {
	VisitIngestKnowledgeResponse(w http.ResponseWriter) error
}

type IngestKnowledge200JSONResponse IngestResult

func (response IngestKnowledge200JSONResponse) VisitIngestKnowledgeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type IngestKnowledge400JSONResponse struct{ JSONBodyBadRequestJSONResponse }

func (response IngestKnowledge400JSONResponse) VisitIngestKnowledgeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type IngestKnowledge401JSONResponse struct{ UnauthorizedJSONResponse }

func (response IngestKnowledge401JSONResponse) VisitIngestKnowledgeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("WWW-Authenticate", fmt.Sprint(response.Headers.WWWAuthenticate))
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response.Body)
}

type IngestKnowledge403JSONResponse struct {
	ScopeOverrideForbiddenJSONResponse
}

func (response IngestKnowledge403JSONResponse) VisitIngestKnowledgeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type IngestKnowledge422JSONResponse struct{ OperationFailedJSONResponse }

func (response IngestKnowledge422JSONResponse) VisitIngestKnowledgeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(422)

	return json.NewEncoder(w).Encode(response)
}

type IngestKnowledge503JSONResponse struct{ UnavailableErrorJSONResponse }

func (response IngestKnowledge503JSONResponse) VisitIngestKnowledgeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)

	return json.NewEncoder(w).Encode(response)
}

type GetOperationRequestObject struct {
	OperationId OperationID `json:"operation_id"`
}

type GetOperationResponseObject interface {
	VisitGetOperationResponse(w http.ResponseWriter) error
}

type GetOperation200JSONResponse OperationResult

func (response GetOperation200JSONResponse) VisitGetOperationResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetOperation400JSONResponse struct {
	OperationIDBadRequestJSONResponse
}

func (response GetOperation400JSONResponse) VisitGetOperationResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type GetOperation401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetOperation401JSONResponse) VisitGetOperationResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("WWW-Authenticate", fmt.Sprint(response.Headers.WWWAuthenticate))
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response.Body)
}

type GetOperation403JSONResponse struct {
	ScopeOverrideForbiddenJSONResponse
}

func (response GetOperation403JSONResponse) VisitGetOperationResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type GetOperation404JSONResponse struct{ NotFoundJSONResponse }

func (response GetOperation404JSONResponse) VisitGetOperationResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetOperation422JSONResponse struct{ OperationFailedJSONResponse }

func (response GetOperation422JSONResponse) VisitGetOperationResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(422)

	return json.NewEncoder(w).Encode(response)
}

type GetOperation503JSONResponse struct{ UnavailableErrorJSONResponse }

func (response GetOperation503JSONResponse) VisitGetOperationResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)

	return json.NewEncoder(w).Encode(response)
}

type RetrieveKnowledgeRequestObject struct {
	Params RetrieveKnowledgeParams
}

type RetrieveKnowledgeResponseObject interface {
	VisitRetrieveKnowledgeResponse(w http.ResponseWriter) error
}

type RetrieveKnowledge200JSONResponse RetrieveResult

func (response RetrieveKnowledge200JSONResponse) VisitRetrieveKnowledgeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type RetrieveKnowledge400JSONResponse struct {
	QueryStringBadRequestJSONResponse
}

func (response RetrieveKnowledge400JSONResponse) VisitRetrieveKnowledgeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type RetrieveKnowledge401JSONResponse struct{ UnauthorizedJSONResponse }

func (response RetrieveKnowledge401JSONResponse) VisitRetrieveKnowledgeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("WWW-Authenticate", fmt.Sprint(response.Headers.WWWAuthenticate))
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response.Body)
}

type RetrieveKnowledge403JSONResponse struct {
	ScopeOverrideForbiddenJSONResponse
}

func (response RetrieveKnowledge403JSONResponse) VisitRetrieveKnowledgeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type RetrieveKnowledge422JSONResponse struct{ OperationFailedJSONResponse }

func (response RetrieveKnowledge422JSONResponse) VisitRetrieveKnowledgeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(422)

	return json.NewEncoder(w).Encode(response)
}

type RetrieveKnowledge503JSONResponse struct{ UnavailableErrorJSONResponse }

func (response RetrieveKnowledge503JSONResponse) VisitRetrieveKnowledgeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Liveness probe
	// (GET /healthz)
	GetHealth(ctx context.Context, request GetHealthRequestObject) (GetHealthResponseObject, error)
	// Readiness probe
	// (GET /readyz)
	GetReady(ctx context.Context, request GetReadyRequestObject) (GetReadyResponseObject, error)
	// Submit one bounded source to the trusted Knowl ingest pipeline
	// (POST /v1/ingest)
	IngestKnowledge(ctx context.Context, request IngestKnowledgeRequestObject) (IngestKnowledgeResponseObject, error)
	// Read one durable Knowl operation status
	// (GET /v1/operations/{operation_id})
	GetOperation(ctx context.Context, request GetOperationRequestObject) (GetOperationResponseObject, error)
	// Retrieve bounded evidence from the trusted Knowl scope
	// (GET /v1/retrieve)
	RetrieveKnowledge(ctx context.Context, request RetrieveKnowledgeRequestObject) (RetrieveKnowledgeResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// GetHealth operation middleware
func (sh *strictHandler) GetHealth(w http.ResponseWriter, r *http.Request) {
	var request GetHealthRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetHealth(ctx, request.(GetHealthRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetHealth")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetHealthResponseObject); ok {
		if err := validResponse.VisitGetHealthResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetReady operation middleware
func (sh *strictHandler) GetReady(w http.ResponseWriter, r *http.Request) {
	var request GetReadyRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetReady(ctx, request.(GetReadyRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetReady")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetReadyResponseObject); ok {
		if err := validResponse.VisitGetReadyResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// IngestKnowledge operation middleware
func (sh *strictHandler) IngestKnowledge(w http.ResponseWriter, r *http.Request) {
	var request IngestKnowledgeRequestObject

	var body IngestKnowledgeJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.IngestKnowledge(ctx, request.(IngestKnowledgeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "IngestKnowledge")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(IngestKnowledgeResponseObject); ok {
		if err := validResponse.VisitIngestKnowledgeResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetOperation operation middleware
func (sh *strictHandler) GetOperation(w http.ResponseWriter, r *http.Request, operationId OperationID) {
	var request GetOperationRequestObject

	request.OperationId = operationId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetOperation(ctx, request.(GetOperationRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetOperation")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetOperationResponseObject); ok {
		if err := validResponse.VisitGetOperationResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// RetrieveKnowledge operation middleware
func (sh *strictHandler) RetrieveKnowledge(w http.ResponseWriter, r *http.Request, params RetrieveKnowledgeParams) {
	var request RetrieveKnowledgeRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.RetrieveKnowledge(ctx, request.(RetrieveKnowledgeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RetrieveKnowledge")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(RetrieveKnowledgeResponseObject); ok {
		if err := validResponse.VisitRetrieveKnowledgeResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}
