//go:build go1.22

// Package knowlapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package knowlapi

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"time"

	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Defines values for CitationKind.
const (
	Raw  CitationKind = "raw"
	Wiki CitationKind = "wiki"
)

// Defines values for ContextPageDisposition.
const (
	BudgetOmitted ContextPageDisposition = "budget_omitted"
	Included      ContextPageDisposition = "included"
	Pending       ContextPageDisposition = "pending"
)

// Defines values for ContextPageSelectionReason.
const (
	ContextPageSelectionReasonHybrid   ContextPageSelectionReason = "hybrid"
	ContextPageSelectionReasonLexical  ContextPageSelectionReason = "lexical"
	ContextPageSelectionReasonNeighbor ContextPageSelectionReason = "neighbor"
	ContextPageSelectionReasonRecent   ContextPageSelectionReason = "recent"
	ContextPageSelectionReasonUnknown  ContextPageSelectionReason = "unknown"
	ContextPageSelectionReasonVector   ContextPageSelectionReason = "vector"
)

// Defines values for HealthResponseStatus.
const (
	Ok HealthResponseStatus = "ok"
)

// Defines values for IngestResultStatus.
const (
	IngestResultStatusCompleted IngestResultStatus = "completed"
	IngestResultStatusFailed    IngestResultStatus = "failed"
	IngestResultStatusQueued    IngestResultStatus = "queued"
	IngestResultStatusRunning   IngestResultStatus = "running"
)

// Defines values for MaintenanceWarningCode.
const (
	CatalogDependencyRejected MaintenanceWarningCode = "catalog.dependency_rejected"
	CitationUnknownSource     MaintenanceWarningCode = "citation.unknown_source"
	LinkOriginalUnresolved    MaintenanceWarningCode = "link.original_unresolved"
)

// Defines values for OKFMetadataEffectiveStatus.
const (
	OKFMetadataEffectiveStatusDeprecated OKFMetadataEffectiveStatus = "deprecated"
	OKFMetadataEffectiveStatusDraft      OKFMetadataEffectiveStatus = "draft"
	OKFMetadataEffectiveStatusStable     OKFMetadataEffectiveStatus = "stable"
)

// Defines values for OKFMetadataStatus.
const (
	OKFMetadataStatusDeprecated OKFMetadataStatus = "deprecated"
	OKFMetadataStatusDraft      OKFMetadataStatus = "draft"
	OKFMetadataStatusStable     OKFMetadataStatus = "stable"
)

// Defines values for OKFMetadataTrustTier.
const (
	HumanReviewed    OKFMetadataTrustTier = "human-reviewed"
	MachineConfirmed OKFMetadataTrustTier = "machine-confirmed"
	Unverified       OKFMetadataTrustTier = "unverified"
)

// Defines values for OperationContextReportOutcome.
const (
	Assembled       OperationContextReportOutcome = "assembled"
	AssemblyFailed  OperationContextReportOutcome = "assembly_failed"
	SelectionFailed OperationContextReportOutcome = "selection_failed"
)

// Defines values for OperationContextReportVersion.
const (
	OperationContextReportVersionN1 OperationContextReportVersion = 1
)

// Defines values for OperationCorrectionReportOutcome.
const (
	OperationCorrectionReportOutcomeAccepted       OperationCorrectionReportOutcome = "accepted"
	OperationCorrectionReportOutcomeCanceled       OperationCorrectionReportOutcome = "canceled"
	OperationCorrectionReportOutcomeDeadline       OperationCorrectionReportOutcome = "deadline"
	OperationCorrectionReportOutcomeExhausted      OperationCorrectionReportOutcome = "exhausted"
	OperationCorrectionReportOutcomeOutputLimit    OperationCorrectionReportOutcome = "output_limit"
	OperationCorrectionReportOutcomeProviderFailed OperationCorrectionReportOutcome = "provider_failed"
	OperationCorrectionReportOutcomeUnavailable    OperationCorrectionReportOutcome = "unavailable"
)

// Defines values for OperationCorrectionReportValidationCode.
const (
	HierarchyPlanInvalid    OperationCorrectionReportValidationCode = "hierarchy_plan_invalid"
	SourcePlanInvalid       OperationCorrectionReportValidationCode = "source_plan_invalid"
	StructuredOutputInvalid OperationCorrectionReportValidationCode = "structured_output_invalid"
)

// Defines values for OperationCorrectionReportVersion.
const (
	OperationCorrectionReportVersionN1 OperationCorrectionReportVersion = 1
)

// Defines values for OperationResultStatus.
const (
	OperationResultStatusCompleted OperationResultStatus = "completed"
	OperationResultStatusFailed    OperationResultStatus = "failed"
	OperationResultStatusQueued    OperationResultStatus = "queued"
	OperationResultStatusRunning   OperationResultStatus = "running"
)

// Defines values for ReadyResponseStatus.
const (
	NotReady ReadyResponseStatus = "not_ready"
	Ready    ReadyResponseStatus = "ready"
)

// Defines values for RetrievalReason.
const (
	RetrievalReasonDeadline             RetrievalReason = "deadline"
	RetrievalReasonDimensionMismatch    RetrievalReason = "dimension_mismatch"
	RetrievalReasonInputLimit           RetrievalReason = "input_limit"
	RetrievalReasonInvalidConfiguration RetrievalReason = "invalid_configuration"
	RetrievalReasonInvalidInput         RetrievalReason = "invalid_input"
	RetrievalReasonInvalidResponse      RetrievalReason = "invalid_response"
	RetrievalReasonModelMismatch        RetrievalReason = "model_mismatch"
	RetrievalReasonProjectionCapacity   RetrievalReason = "projection_capacity"
	RetrievalReasonProjectionDrift      RetrievalReason = "projection_drift"
	RetrievalReasonProjectionNotReady   RetrievalReason = "projection_not_ready"
	RetrievalReasonResponseLimit        RetrievalReason = "response_limit"
	RetrievalReasonUnavailable          RetrievalReason = "unavailable"
)

// Defines values for RetrievalReportEffective.
const (
	RetrievalReportEffectiveDegraded RetrievalReportEffective = "degraded"
	RetrievalReportEffectiveFailed   RetrievalReportEffective = "failed"
	RetrievalReportEffectiveHybrid   RetrievalReportEffective = "hybrid"
	RetrievalReportEffectiveLexical  RetrievalReportEffective = "lexical"
)

// Defines values for RetrievalReportRequested.
const (
	RetrievalReportRequestedHybrid  RetrievalReportRequested = "hybrid"
	RetrievalReportRequestedLexical RetrievalReportRequested = "lexical"
)

// Defines values for RetrievalStatusEffective.
const (
	RetrievalStatusEffectiveDegraded RetrievalStatusEffective = "degraded"
	RetrievalStatusEffectiveFailed   RetrievalStatusEffective = "failed"
	RetrievalStatusEffectiveHybrid   RetrievalStatusEffective = "hybrid"
	RetrievalStatusEffectiveLexical  RetrievalStatusEffective = "lexical"
)

// Defines values for RetrievalStatusReason.
const (
	Deadline             RetrievalStatusReason = "deadline"
	DimensionMismatch    RetrievalStatusReason = "dimension_mismatch"
	InputLimit           RetrievalStatusReason = "input_limit"
	InvalidConfiguration RetrievalStatusReason = "invalid_configuration"
	InvalidInput         RetrievalStatusReason = "invalid_input"
	InvalidResponse      RetrievalStatusReason = "invalid_response"
	ModelMismatch        RetrievalStatusReason = "model_mismatch"
	ProjectionCapacity   RetrievalStatusReason = "projection_capacity"
	ProjectionDrift      RetrievalStatusReason = "projection_drift"
	ProjectionNotReady   RetrievalStatusReason = "projection_not_ready"
	ResponseLimit        RetrievalStatusReason = "response_limit"
	Unavailable          RetrievalStatusReason = "unavailable"
)

// Defines values for VectorProjectionStatusState.
const (
	VectorInvalid    VectorProjectionStatusState = "invalid"
	VectorNotChecked VectorProjectionStatusState = "not_checked"
	VectorReady      VectorProjectionStatusState = "ready"
)

// Citation defines model for Citation.
type Citation struct {
	Kind      CitationKind `json:"kind"`
	PageId    *string      `json:"page_id,omitempty"`
	Path      *string      `json:"path,omitempty"`
	Reference string       `json:"reference"`
	SourceRef *string      `json:"source_ref,omitempty"`
	Untrusted bool         `json:"untrusted"`
}

// CitationKind defines model for Citation.Kind.
type CitationKind string

// ContextBudget defines model for ContextBudget.
type ContextBudget struct {
	IncludedCount DiagnosticCount `json:"included_count"`
	MaxBytes      int             `json:"max_bytes"`

	// OmittedCount Actual candidates omitted by the request byte budget; pending candidates are not counted.
	OmittedCount DiagnosticCount `json:"omitted_count"`

	// UsedBytes Serialized accepted request bytes, or last measured accepted prefix on partial failure. Absent when preflight stopped exact measurement; measured required overflow can exceed max_bytes.
	UsedBytes *DiagnosticCount `json:"used_bytes,omitempty"`
}

// ContextPage defines model for ContextPage.
type ContextPage struct {
	Disposition ContextPageDisposition `json:"disposition"`

	// PageId Canonical relative ordinary page ID, additionally limited to 2048 UTF-8 bytes.
	PageId string `json:"page_id"`

	// SelectionReason First actual selection phase; unsupported custom indexes report unknown.
	SelectionReason ContextPageSelectionReason `json:"selection_reason"`
}

// ContextPageDisposition defines model for ContextPage.Disposition.
type ContextPageDisposition string

// ContextPageSelectionReason First actual selection phase; unsupported custom indexes report unknown.
type ContextPageSelectionReason string

// DiagnosticCount defines model for DiagnosticCount.
type DiagnosticCount = int

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error string `json:"error"`
}

// EvidenceItem defines model for EvidenceItem.
type EvidenceItem struct {
	DocumentId      *string           `json:"document_id,omitempty"`
	Okf             *OKFMetadata      `json:"okf,omitempty"`
	PageId          string            `json:"page_id"`
	Revision        *string           `json:"revision,omitempty"`
	Snippet         string            `json:"snippet"`
	SourceDocuments *[]SourceDocument `json:"source_documents,omitempty"`
	SourceId        *string           `json:"source_id,omitempty"`
	SourceRefs      *[]string         `json:"source_refs,omitempty"`
	Title           string            `json:"title"`
	Untrusted       bool              `json:"untrusted"`
	Uri             *string           `json:"uri,omitempty"`
}

// Failure defines model for Failure.
type Failure struct {
	Class       string `json:"class"`
	OperationId string `json:"operation_id"`

	// Reason Stable application failure code when classified; no provider error text.
	Reason *string `json:"reason,omitempty"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	Service string               `json:"service"`
	Status  HealthResponseStatus `json:"status"`
}

// HealthResponseStatus defines model for HealthResponse.Status.
type HealthResponseStatus string

// IngestRequest defines model for IngestRequest.
type IngestRequest struct {
	// Content Text already obtained by the caller. Supply exactly one of content or uri.
	Content        *string `json:"content,omitempty"`
	IdempotencyKey *string `json:"idempotency_key,omitempty"`
	MediaType      *string `json:"media_type,omitempty"`

	// Origin Source identity hint for supplied content, such as its original URL. Not fetched.
	Origin *string `json:"origin,omitempty"`

	// Uri URI string stored as reference text, without downloading the document. Use content for document text; supply exactly one of content or uri.
	Uri *string `json:"uri,omitempty"`
}

// IngestResult defines model for IngestResult.
type IngestResult struct {
	OperationId string             `json:"operation_id"`
	Retrieval   *RetrievalStatus   `json:"retrieval,omitempty"`
	Status      IngestResultStatus `json:"status"`
}

// IngestResultStatus defines model for IngestResult.Status.
type IngestResultStatus string

// MaintenanceWarning defines model for MaintenanceWarning.
type MaintenanceWarning struct {
	Code MaintenanceWarningCode `json:"code"`

	// Path Safe relative identifier, additionally limited to 2048 UTF-8 bytes.
	Path string `json:"path"`

	// Target Safe relative identifier when available; no URL or arbitrary message.
	Target *string `json:"target,omitempty"`
}

// MaintenanceWarningCode defines model for MaintenanceWarning.Code.
type MaintenanceWarningCode string

// OKFAttester defines model for OKFAttester.
type OKFAttester struct {
	Extensions *OKFExtensions `json:"extensions,omitempty"`
	Resource   string         `json:"resource"`
}

// OKFExecutor defines model for OKFExecutor.
type OKFExecutor struct {
	Extensions *OKFExtensions `json:"extensions,omitempty"`
	Receipt    *[]string      `json:"receipt,omitempty"`
	Resource   string         `json:"resource"`
}

// OKFExtensions defines model for OKFExtensions.
type OKFExtensions map[string]interface{}

// OKFGeneration defines model for OKFGeneration.
type OKFGeneration struct {
	At         *time.Time     `json:"at,omitempty"`
	By         string         `json:"by"`
	Extensions *OKFExtensions `json:"extensions,omitempty"`
}

// OKFMetadata defines model for OKFMetadata.
type OKFMetadata struct {
	Attester        *OKFAttester                `json:"attester,omitempty"`
	Computation     *string                     `json:"computation,omitempty"`
	Description     *string                     `json:"description,omitempty"`
	EffectiveStatus *OKFMetadataEffectiveStatus `json:"effective_status,omitempty"`
	Executor        *OKFExecutor                `json:"executor,omitempty"`
	Extensions      *OKFExtensions              `json:"extensions,omitempty"`
	Generated       *OKFGeneration              `json:"generated,omitempty"`
	Parameters      *[]OKFParameter             `json:"parameters,omitempty"`
	Resource        *string                     `json:"resource,omitempty"`
	Runtime         *string                     `json:"runtime,omitempty"`
	Sources         *[]OKFSource                `json:"sources,omitempty"`
	Stale           *bool                       `json:"stale,omitempty"`
	StaleAfter      *time.Time                  `json:"stale_after,omitempty"`
	Status          *OKFMetadataStatus          `json:"status,omitempty"`
	Tags            *[]string                   `json:"tags,omitempty"`
	Title           *string                     `json:"title,omitempty"`
	TrustTier       *OKFMetadataTrustTier       `json:"trust_tier,omitempty"`
	Type            string                      `json:"type"`
	UsageWindow     *OKFUsageWindow             `json:"usage_window,omitempty"`
	Verified        *[]OKFVerification          `json:"verified,omitempty"`
}

// OKFMetadataEffectiveStatus defines model for OKFMetadata.EffectiveStatus.
type OKFMetadataEffectiveStatus string

// OKFMetadataStatus defines model for OKFMetadata.Status.
type OKFMetadataStatus string

// OKFMetadataTrustTier defines model for OKFMetadata.TrustTier.
type OKFMetadataTrustTier string

// OKFParameter defines model for OKFParameter.
type OKFParameter struct {
	Extensions *OKFExtensions `json:"extensions,omitempty"`
	Name       string         `json:"name"`
	Required   bool           `json:"required"`
	Type       string         `json:"type"`
}

// OKFSource defines model for OKFSource.
type OKFSource struct {
	Author       *string         `json:"author,omitempty"`
	Extensions   *OKFExtensions  `json:"extensions,omitempty"`
	Id           *string         `json:"id,omitempty"`
	LastModified *time.Time      `json:"last_modified,omitempty"`
	Resource     string          `json:"resource"`
	Title        *string         `json:"title,omitempty"`
	UsageCount   *uint64         `json:"usage_count,omitempty"`
	UsageWindow  *OKFUsageWindow `json:"usage_window,omitempty"`
}

// OKFUsageWindow defines model for OKFUsageWindow.
type OKFUsageWindow struct {
	Extensions *OKFExtensions `json:"extensions,omitempty"`
	From       time.Time      `json:"from"`
	To         time.Time      `json:"to"`
}

// OKFVerification defines model for OKFVerification.
type OKFVerification struct {
	At         time.Time      `json:"at"`
	By         string         `json:"by"`
	Extensions *OKFExtensions `json:"extensions,omitempty"`
}

// OperationContextReport One immutable snapshot per producing work attempt; at most 32 KiB. A crash before finalization can leave it absent.
type OperationContextReport struct {
	Budget *ContextBudget `json:"budget,omitempty"`

	// CandidateCount Unique ordinary candidates eligible under the factual page allowance, excluding controls and duplicates. Not a wiki-wide omission count.
	CandidateCount *DiagnosticCount `json:"candidate_count,omitempty"`

	// CatalogCount Number of catalogs observed when inspection succeeded.
	CatalogCount *DiagnosticCount `json:"catalog_count,omitempty"`

	// EntriesOmitted Candidate entries omitted from this diagnostic list by its bounds; distinct from budget exclusions.
	EntriesOmitted DiagnosticCount               `json:"entries_omitted"`
	Outcome        OperationContextReportOutcome `json:"outcome"`
	Pages          *[]ContextPage                `json:"pages,omitempty"`

	// VectorProjection Check observed during the producing attempt, never current projection readiness at poll time.
	VectorProjection *VectorProjectionStatus       `json:"vector_projection,omitempty"`
	Version          OperationContextReportVersion `json:"version"`
	WorkAttempt      DiagnosticCount               `json:"work_attempt"`
}

// OperationContextReportOutcome defines model for OperationContextReport.Outcome.
type OperationContextReportOutcome string

// OperationContextReportVersion defines model for OperationContextReport.Version.
type OperationContextReportVersion int

// OperationCorrectionReport One immutable report per producing work attempt; at most 1 KiB. Counters measure actual generation turns and accepted-prefix output text across all turns. Unavailable counters are absent. A crash before finalization can leave the report absent.
type OperationCorrectionReport struct {
	Corrections    *int                                     `json:"corrections,omitempty"`
	DeadlineNanos  int64                                    `json:"deadline_nanos"`
	MaxCorrections int                                      `json:"max_corrections"`
	MaxOutputBytes int                                      `json:"max_output_bytes"`
	Outcome        OperationCorrectionReportOutcome         `json:"outcome"`
	OutputBytes    *int                                     `json:"output_bytes,omitempty"`
	Turns          *int                                     `json:"turns,omitempty"`
	ValidationCode *OperationCorrectionReportValidationCode `json:"validation_code,omitempty"`
	Version        OperationCorrectionReportVersion         `json:"version"`
	WorkAttempt    DiagnosticCount                          `json:"work_attempt"`
}

// OperationCorrectionReportOutcome defines model for OperationCorrectionReport.Outcome.
type OperationCorrectionReportOutcome string

// OperationCorrectionReportValidationCode defines model for OperationCorrectionReport.ValidationCode.
type OperationCorrectionReportValidationCode string

// OperationCorrectionReportVersion defines model for OperationCorrectionReport.Version.
type OperationCorrectionReportVersion int

// OperationDetails Bounded stored facts. Missing evidence is unavailable. Reads do not rerun selection or inference. Details serialize to less than 96 KiB.
type OperationDetails struct {
	// Context One immutable snapshot per producing work attempt; at most 32 KiB. A crash before finalization can leave it absent.
	Context *OperationContextReport `json:"context,omitempty"`

	// Correction One immutable report per producing work attempt; at most 1 KiB. Counters measure actual generation turns and accepted-prefix output text across all turns. Unavailable counters are absent. A crash before finalization can leave the report absent.
	Correction       *OperationCorrectionReport `json:"correction,omitempty"`
	Execution        *OperationExecutionDetails `json:"execution,omitempty"`
	Plan             *OperationPlanSummary      `json:"plan,omitempty"`
	Retrieval        *RetrievalReport           `json:"retrieval,omitempty"`
	RetrievalAttempt *DiagnosticCount           `json:"retrieval_attempt,omitempty"`
	Warnings         *[]MaintenanceWarning      `json:"warnings,omitempty"`
	WarningsOmitted  *DiagnosticCount           `json:"warnings_omitted,omitempty"`
}

// OperationExecutionDetails defines model for OperationExecutionDetails.
type OperationExecutionDetails struct {
	// ApplyAttempt Existing canonical apply-attempt counter, not inference calls.
	ApplyAttempt     DiagnosticCount `json:"apply_attempt"`
	ManualRetryCount DiagnosticCount `json:"manual_retry_count"`
	ReadyAt          *time.Time      `json:"ready_at,omitempty"`
	RetryAttempt     DiagnosticCount `json:"retry_attempt"`
	WorkAttempt      DiagnosticCount `json:"work_attempt"`
}

// OperationPlanSummary defines model for OperationPlanSummary.
type OperationPlanSummary struct {
	// Digest Stored validated/staged SHA-256 digest, without edits or rationale.
	Digest string `json:"digest"`

	// FileCount Stored number of staged files when known. Legacy digest-only rows omit it.
	FileCount *DiagnosticCount `json:"file_count,omitempty"`
}

// OperationResult defines model for OperationResult.
type OperationResult struct {
	// Details Bounded stored facts. Missing evidence is unavailable. Reads do not rerun selection or inference. Details serialize to less than 96 KiB.
	Details   *OperationDetails     `json:"details,omitempty"`
	Failure   *Failure              `json:"failure,omitempty"`
	Id        string                `json:"id"`
	Retrieval *RetrievalStatus      `json:"retrieval,omitempty"`
	Status    OperationResultStatus `json:"status"`
	UpdatedAt time.Time             `json:"updated_at"`
}

// OperationResultStatus defines model for OperationResult.Status.
type OperationResultStatus string

// ReadyResponse defines model for ReadyResponse.
type ReadyResponse struct {
	// Scope Trusted scope reported only when the host is ready.
	Scope   *string             `json:"scope,omitempty"`
	Service string              `json:"service"`
	Status  ReadyResponseStatus `json:"status"`
}

// ReadyResponseStatus defines model for ReadyResponse.Status.
type ReadyResponseStatus string

// RetrievalReason defines model for RetrievalReason.
type RetrievalReason string

// RetrievalReport defines model for RetrievalReport.
type RetrievalReport struct {
	Effective          RetrievalReportEffective `json:"effective"`
	FusedCandidates    int                      `json:"fused_candidates"`
	IndexOmittedChunks DiagnosticCount          `json:"index_omitted_chunks"`
	IndexOmittedRunes  DiagnosticCount          `json:"index_omitted_runes"`
	LexicalCandidates  int                      `json:"lexical_candidates"`

	// ModelSpace Non-secret fingerprint, without model endpoint or credentials.
	ModelSpace        *string                  `json:"model_space,omitempty"`
	QueryOmittedRunes DiagnosticCount          `json:"query_omitted_runes"`
	Reason            *RetrievalReason         `json:"reason,omitempty"`
	Requested         RetrievalReportRequested `json:"requested"`
	ScannedChunks     int                      `json:"scanned_chunks"`
	VectorCandidates  int                      `json:"vector_candidates"`
}

// RetrievalReportEffective defines model for RetrievalReport.Effective.
type RetrievalReportEffective string

// RetrievalReportRequested defines model for RetrievalReport.Requested.
type RetrievalReportRequested string

// RetrievalStatus defines model for RetrievalStatus.
type RetrievalStatus struct {
	Effective RetrievalStatusEffective `json:"effective"`
	Reason    *RetrievalStatusReason   `json:"reason,omitempty"`
}

// RetrievalStatusEffective defines model for RetrievalStatus.Effective.
type RetrievalStatusEffective string

// RetrievalStatusReason defines model for RetrievalStatus.Reason.
type RetrievalStatusReason string

// RetrieveResult defines model for RetrieveResult.
type RetrieveResult struct {
	Citations *[]Citation      `json:"citations,omitempty"`
	Evidence  []EvidenceItem   `json:"evidence"`
	Query     string           `json:"query"`
	Retrieval *RetrievalStatus `json:"retrieval,omitempty"`
}

// SourceDocument defines model for SourceDocument.
type SourceDocument struct {
	DocumentId string `json:"document_id"`
	Revision   string `json:"revision"`
	SourceId   string `json:"source_id"`
	Uri        string `json:"uri"`
}

// VectorProjectionStatus Check observed during the producing attempt, never current projection readiness at poll time.
type VectorProjectionStatus struct {
	Reason *RetrievalReason            `json:"reason,omitempty"`
	State  VectorProjectionStatusState `json:"state"`
}

// VectorProjectionStatusState defines model for VectorProjectionStatus.State.
type VectorProjectionStatusState string

// OperationID defines model for OperationID.
type OperationID = string

// RetrieveQuery defines model for RetrieveQuery.
type RetrieveQuery = string

// RetrieveSource defines model for RetrieveSource.
type RetrieveSource = []string

// JSONBodyBadRequest defines model for JSONBodyBadRequest.
type JSONBodyBadRequest = ErrorResponse

// NotFound defines model for NotFound.
type NotFound = ErrorResponse

// OperationFailed defines model for OperationFailed.
type OperationFailed = ErrorResponse

// OperationIDBadRequest defines model for OperationIDBadRequest.
type OperationIDBadRequest = ErrorResponse

// QueryStringBadRequest defines model for QueryStringBadRequest.
type QueryStringBadRequest = ErrorResponse

// ScopeOverrideForbidden defines model for ScopeOverrideForbidden.
type ScopeOverrideForbidden = ErrorResponse

// Unauthorized defines model for Unauthorized.
type Unauthorized = ErrorResponse

// UnavailableError defines model for UnavailableError.
type UnavailableError = ErrorResponse

// RetrieveKnowledgeParams defines parameters for RetrieveKnowledge.
type RetrieveKnowledgeParams struct {
	// Query Free-text retrieval query.
	Query RetrieveQuery `form:"query" json:"query"`

	// Source Optional repeatable source identity filter. Empty means all sources and curated pages.
	Source *RetrieveSource `form:"source,omitempty" json:"source,omitempty"`
}

// IngestKnowledgeJSONRequestBody defines body for IngestKnowledge for application/json ContentType.
type IngestKnowledgeJSONRequestBody = IngestRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Liveness probe
	// (GET /healthz)
	GetHealth(w http.ResponseWriter, r *http.Request)
	// Readiness probe
	// (GET /readyz)
	GetReady(w http.ResponseWriter, r *http.Request)
	// Submit supplied text or a URI reference to the trusted ingest pipeline
	// (POST /v1/ingest)
	IngestKnowledge(w http.ResponseWriter, r *http.Request)
	// Read one durable Knowl operation status
	// (GET /v1/operations/{operation_id})
	GetOperation(w http.ResponseWriter, r *http.Request, operationId OperationID)
	// Retrieve bounded evidence from the trusted Knowl scope
	// (GET /v1/retrieve)
	RetrieveKnowledge(w http.ResponseWriter, r *http.Request, params RetrieveKnowledgeParams)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetReady operation middleware
func (siw *ServerInterfaceWrapper) GetReady(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetReady(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// IngestKnowledge operation middleware
func (siw *ServerInterfaceWrapper) IngestKnowledge(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.IngestKnowledge(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetOperation operation middleware
func (siw *ServerInterfaceWrapper) GetOperation(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "operation_id" -------------
	var operationId OperationID

	err = runtime.BindStyledParameterWithOptions("simple", "operation_id", r.PathValue("operation_id"), &operationId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "operation_id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetOperation(w, r, operationId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RetrieveKnowledge operation middleware
func (siw *ServerInterfaceWrapper) RetrieveKnowledge(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params RetrieveKnowledgeParams

	// ------------- Required query parameter "query" -------------

	if paramValue := r.URL.Query().Get("query"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "query"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "query", r.URL.Query(), &params.Query)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "query", Err: err})
		return
	}

	// ------------- Optional query parameter "source" -------------

	err = runtime.BindQueryParameter("form", true, false, "source", r.URL.Query(), &params.Source)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "source", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RetrieveKnowledge(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("GET "+options.BaseURL+"/healthz", wrapper.GetHealth)
	m.HandleFunc("GET "+options.BaseURL+"/readyz", wrapper.GetReady)
	m.HandleFunc("POST "+options.BaseURL+"/v1/ingest", wrapper.IngestKnowledge)
	m.HandleFunc("GET "+options.BaseURL+"/v1/operations/{operation_id}", wrapper.GetOperation)
	m.HandleFunc("GET "+options.BaseURL+"/v1/retrieve", wrapper.RetrieveKnowledge)

	return m
}

type JSONBodyBadRequestJSONResponse ErrorResponse

type NotFoundJSONResponse ErrorResponse

type OperationFailedJSONResponse ErrorResponse

type OperationIDBadRequestJSONResponse ErrorResponse

type QueryStringBadRequestJSONResponse ErrorResponse

type ScopeOverrideForbiddenJSONResponse ErrorResponse

type UnauthorizedResponseHeaders struct {
	WWWAuthenticate string
}
type UnauthorizedJSONResponse struct {
	Body ErrorResponse

	Headers UnauthorizedResponseHeaders
}

type UnavailableErrorJSONResponse ErrorResponse

type GetHealthRequestObject struct {
}

type GetHealthResponseObject interface {
	VisitGetHealthResponse(w http.ResponseWriter) error
}

type GetHealth200JSONResponse HealthResponse

func (response GetHealth200JSONResponse) VisitGetHealthResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetReadyRequestObject struct {
}

type GetReadyResponseObject interface {
	VisitGetReadyResponse(w http.ResponseWriter) error
}

type GetReady200JSONResponse ReadyResponse

func (response GetReady200JSONResponse) VisitGetReadyResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetReady503JSONResponse ReadyResponse

func (response GetReady503JSONResponse) VisitGetReadyResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)

	return json.NewEncoder(w).Encode(response)
}

type IngestKnowledgeRequestObject struct {
	Body *IngestKnowledgeJSONRequestBody
}

type IngestKnowledgeResponseObject interface {
	VisitIngestKnowledgeResponse(w http.ResponseWriter) error
}

type IngestKnowledge200JSONResponse IngestResult

func (response IngestKnowledge200JSONResponse) VisitIngestKnowledgeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type IngestKnowledge400JSONResponse struct{ JSONBodyBadRequestJSONResponse }

func (response IngestKnowledge400JSONResponse) VisitIngestKnowledgeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type IngestKnowledge401JSONResponse struct{ UnauthorizedJSONResponse }

func (response IngestKnowledge401JSONResponse) VisitIngestKnowledgeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("WWW-Authenticate", fmt.Sprint(response.Headers.WWWAuthenticate))
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response.Body)
}

type IngestKnowledge403JSONResponse struct {
	ScopeOverrideForbiddenJSONResponse
}

func (response IngestKnowledge403JSONResponse) VisitIngestKnowledgeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type IngestKnowledge422JSONResponse struct{ OperationFailedJSONResponse }

func (response IngestKnowledge422JSONResponse) VisitIngestKnowledgeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(422)

	return json.NewEncoder(w).Encode(response)
}

type IngestKnowledge503JSONResponse struct{ UnavailableErrorJSONResponse }

func (response IngestKnowledge503JSONResponse) VisitIngestKnowledgeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)

	return json.NewEncoder(w).Encode(response)
}

type GetOperationRequestObject struct {
	OperationId OperationID `json:"operation_id"`
}

type GetOperationResponseObject interface {
	VisitGetOperationResponse(w http.ResponseWriter) error
}

type GetOperation200JSONResponse OperationResult

func (response GetOperation200JSONResponse) VisitGetOperationResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetOperation400JSONResponse struct {
	OperationIDBadRequestJSONResponse
}

func (response GetOperation400JSONResponse) VisitGetOperationResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type GetOperation401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetOperation401JSONResponse) VisitGetOperationResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("WWW-Authenticate", fmt.Sprint(response.Headers.WWWAuthenticate))
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response.Body)
}

type GetOperation403JSONResponse struct {
	ScopeOverrideForbiddenJSONResponse
}

func (response GetOperation403JSONResponse) VisitGetOperationResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type GetOperation404JSONResponse struct{ NotFoundJSONResponse }

func (response GetOperation404JSONResponse) VisitGetOperationResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetOperation422JSONResponse struct{ OperationFailedJSONResponse }

func (response GetOperation422JSONResponse) VisitGetOperationResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(422)

	return json.NewEncoder(w).Encode(response)
}

type GetOperation503JSONResponse struct{ UnavailableErrorJSONResponse }

func (response GetOperation503JSONResponse) VisitGetOperationResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)

	return json.NewEncoder(w).Encode(response)
}

type RetrieveKnowledgeRequestObject struct {
	Params RetrieveKnowledgeParams
}

type RetrieveKnowledgeResponseObject interface {
	VisitRetrieveKnowledgeResponse(w http.ResponseWriter) error
}

type RetrieveKnowledge200JSONResponse RetrieveResult

func (response RetrieveKnowledge200JSONResponse) VisitRetrieveKnowledgeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type RetrieveKnowledge400JSONResponse struct {
	QueryStringBadRequestJSONResponse
}

func (response RetrieveKnowledge400JSONResponse) VisitRetrieveKnowledgeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type RetrieveKnowledge401JSONResponse struct{ UnauthorizedJSONResponse }

func (response RetrieveKnowledge401JSONResponse) VisitRetrieveKnowledgeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("WWW-Authenticate", fmt.Sprint(response.Headers.WWWAuthenticate))
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response.Body)
}

type RetrieveKnowledge403JSONResponse struct {
	ScopeOverrideForbiddenJSONResponse
}

func (response RetrieveKnowledge403JSONResponse) VisitRetrieveKnowledgeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type RetrieveKnowledge422JSONResponse struct{ OperationFailedJSONResponse }

func (response RetrieveKnowledge422JSONResponse) VisitRetrieveKnowledgeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(422)

	return json.NewEncoder(w).Encode(response)
}

type RetrieveKnowledge503JSONResponse struct{ UnavailableErrorJSONResponse }

func (response RetrieveKnowledge503JSONResponse) VisitRetrieveKnowledgeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Liveness probe
	// (GET /healthz)
	GetHealth(ctx context.Context, request GetHealthRequestObject) (GetHealthResponseObject, error)
	// Readiness probe
	// (GET /readyz)
	GetReady(ctx context.Context, request GetReadyRequestObject) (GetReadyResponseObject, error)
	// Submit supplied text or a URI reference to the trusted ingest pipeline
	// (POST /v1/ingest)
	IngestKnowledge(ctx context.Context, request IngestKnowledgeRequestObject) (IngestKnowledgeResponseObject, error)
	// Read one durable Knowl operation status
	// (GET /v1/operations/{operation_id})
	GetOperation(ctx context.Context, request GetOperationRequestObject) (GetOperationResponseObject, error)
	// Retrieve bounded evidence from the trusted Knowl scope
	// (GET /v1/retrieve)
	RetrieveKnowledge(ctx context.Context, request RetrieveKnowledgeRequestObject) (RetrieveKnowledgeResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// GetHealth operation middleware
func (sh *strictHandler) GetHealth(w http.ResponseWriter, r *http.Request) {
	var request GetHealthRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetHealth(ctx, request.(GetHealthRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetHealth")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetHealthResponseObject); ok {
		if err := validResponse.VisitGetHealthResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetReady operation middleware
func (sh *strictHandler) GetReady(w http.ResponseWriter, r *http.Request) {
	var request GetReadyRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetReady(ctx, request.(GetReadyRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetReady")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetReadyResponseObject); ok {
		if err := validResponse.VisitGetReadyResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// IngestKnowledge operation middleware
func (sh *strictHandler) IngestKnowledge(w http.ResponseWriter, r *http.Request) {
	var request IngestKnowledgeRequestObject

	var body IngestKnowledgeJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.IngestKnowledge(ctx, request.(IngestKnowledgeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "IngestKnowledge")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(IngestKnowledgeResponseObject); ok {
		if err := validResponse.VisitIngestKnowledgeResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetOperation operation middleware
func (sh *strictHandler) GetOperation(w http.ResponseWriter, r *http.Request, operationId OperationID) {
	var request GetOperationRequestObject

	request.OperationId = operationId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetOperation(ctx, request.(GetOperationRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetOperation")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetOperationResponseObject); ok {
		if err := validResponse.VisitGetOperationResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// RetrieveKnowledge operation middleware
func (sh *strictHandler) RetrieveKnowledge(w http.ResponseWriter, r *http.Request, params RetrieveKnowledgeParams) {
	var request RetrieveKnowledgeRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.RetrieveKnowledge(ctx, request.(RetrieveKnowledgeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RetrieveKnowledge")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(RetrieveKnowledgeResponseObject); ok {
		if err := validResponse.VisitRetrieveKnowledgeResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}
