//go:build go1.22

// Package knowlapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package knowlapi

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"time"

	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Defines values for CitationKind.
const (
	Raw  CitationKind = "raw"
	Wiki CitationKind = "wiki"
)

// Defines values for HealthResponseStatus.
const (
	Ok HealthResponseStatus = "ok"
)

// Defines values for OperationStatus.
const (
	Applying       OperationStatus = "applying"
	AwaitingReview OperationStatus = "awaiting_review"
	Committed      OperationStatus = "committed"
	Failed         OperationStatus = "failed"
	Planned        OperationStatus = "planned"
	Received       OperationStatus = "received"
)

// Defines values for ReadyResponseStatus.
const (
	NotReady ReadyResponseStatus = "not_ready"
	Ready    ReadyResponseStatus = "ready"
)

// ApplyResult defines model for ApplyResult.
type ApplyResult struct {
	Commit    *ContentCommit `json:"commit,omitempty"`
	Operation Operation      `json:"operation"`
}

// Citation defines model for Citation.
type Citation struct {
	Kind      CitationKind `json:"kind"`
	PageId    *string      `json:"page_id,omitempty"`
	Path      *string      `json:"path,omitempty"`
	Reference string       `json:"reference"`
	SourceRef *string      `json:"source_ref,omitempty"`
	Untrusted bool         `json:"untrusted"`
}

// CitationKind defines model for Citation.Kind.
type CitationKind string

// ContentCommit defines model for ContentCommit.
type ContentCommit struct {
	CommittedAt time.Time         `json:"committed_at"`
	Files       []string          `json:"files"`
	Generation  string            `json:"generation"`
	OperationId string            `json:"operation_id"`
	Snapshot    WorkspaceSnapshot `json:"snapshot"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error string `json:"error"`
}

// Failure defines model for Failure.
type Failure struct {
	Class       string `json:"class"`
	OperationId string `json:"operation_id"`
}

// FileEdit defines model for FileEdit.
type FileEdit struct {
	Content        []byte  `json:"content"`
	ExpectedDigest *string `json:"expected_digest,omitempty"`
	Path           string  `json:"path"`
}

// FilingRequest defines model for FilingRequest.
type FilingRequest struct {
	Plan   ModelEditPlan `json:"plan"`
	Query  string        `json:"query"`
	Result QueryResult   `json:"result"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	Service string               `json:"service"`
	Status  HealthResponseStatus `json:"status"`
}

// HealthResponseStatus defines model for HealthResponse.Status.
type HealthResponseStatus string

// IngestResult defines model for IngestResult.
type IngestResult struct {
	Commit    *ContentCommit    `json:"commit,omitempty"`
	Operation Operation         `json:"operation"`
	Plan      ValidatedEditPlan `json:"plan"`
	Staged    StagedChange      `json:"staged"`
}

// LinkReference defines model for LinkReference.
type LinkReference struct {
	From      string `json:"from"`
	Relation  string `json:"relation"`
	To        string `json:"to"`
	Untrusted bool   `json:"untrusted"`
}

// LintFinding defines model for LintFinding.
type LintFinding struct {
	Code       string    `json:"code"`
	Message    string    `json:"message"`
	PageId     *string   `json:"page_id,omitempty"`
	Path       *string   `json:"path,omitempty"`
	Severity   string    `json:"severity"`
	SourceRefs *[]string `json:"source_refs,omitempty"`
	Suggestion *bool     `json:"suggestion,omitempty"`
}

// LintReport defines model for LintReport.
type LintReport struct {
	CheckedAt time.Time     `json:"checked_at"`
	Findings  []LintFinding `json:"findings"`
	Scope     string        `json:"scope"`
}

// ModelEditPlan defines model for ModelEditPlan.
type ModelEditPlan struct {
	Edits        []FileEdit `json:"edits"`
	Rationale    *string    `json:"rationale,omitempty"`
	SchemaDigest string     `json:"schema_digest"`
	SourceRefs   []string   `json:"source_refs"`
}

// Operation defines model for Operation.
type Operation struct {
	Attempt   int             `json:"attempt"`
	Failure   *Failure        `json:"failure,omitempty"`
	Id        string          `json:"id"`
	Key       OperationKey    `json:"key"`
	Status    OperationStatus `json:"status"`
	UpdatedAt time.Time       `json:"updated_at"`
}

// OperationStatus defines model for Operation.Status.
type OperationStatus string

// OperationKey defines model for OperationKey.
type OperationKey struct {
	Scope   string        `json:"scope"`
	Source  SourceRef     `json:"source"`
	Version SourceVersion `json:"version"`
}

// PageReference defines model for PageReference.
type PageReference struct {
	Id         string   `json:"id"`
	Path       string   `json:"path"`
	Snippet    string   `json:"snippet"`
	SourceRefs []string `json:"source_refs"`
	Title      string   `json:"title"`
	Untrusted  bool     `json:"untrusted"`
}

// PageSnapshot defines model for PageSnapshot.
type PageSnapshot struct {
	Content    string    `json:"content"`
	Digest     string    `json:"digest"`
	Id         string    `json:"id"`
	Path       string    `json:"path"`
	SourceRefs *[]string `json:"source_refs,omitempty"`
	Title      string    `json:"title"`
	Untrusted  bool      `json:"untrusted"`
	UpdatedAt  time.Time `json:"updated_at"`
}

// QueryResult defines model for QueryResult.
type QueryResult struct {
	Citations []Citation      `json:"citations"`
	Links     []LinkReference `json:"links"`
	Pages     []PageReference `json:"pages"`
	Query     string          `json:"query"`
	Scope     string          `json:"scope"`
}

// ReadyResponse defines model for ReadyResponse.
type ReadyResponse struct {
	// Scope Trusted scope reported only when the host is ready.
	Scope   *string             `json:"scope,omitempty"`
	Service string              `json:"service"`
	Status  ReadyResponseStatus `json:"status"`
}

// ReadyResponseStatus defines model for ReadyResponse.Status.
type ReadyResponseStatus string

// SourceEnvelope defines model for SourceEnvelope.
type SourceEnvelope struct {
	// Content Base64-encoded bounded source payload.
	Content    []byte                  `json:"content"`
	MediaType  *string                 `json:"media_type,omitempty"`
	Provenance *map[string]interface{} `json:"provenance,omitempty"`
	ReceivedAt *time.Time              `json:"received_at,omitempty"`

	// Scope Optional trusted scope. When omitted, the host fills its configured scope.
	Scope   *string       `json:"scope,omitempty"`
	Source  SourceRef     `json:"source"`
	Version SourceVersion `json:"version"`
}

// SourceRef defines model for SourceRef.
type SourceRef struct {
	Adapter string `json:"adapter"`
	Id      string `json:"id"`
}

// SourceVersion defines model for SourceVersion.
type SourceVersion struct {
	Digest  string `json:"digest"`
	Version string `json:"version"`
}

// StagedChange defines model for StagedChange.
type StagedChange struct {
	CreatedAt   time.Time `json:"created_at"`
	Digest      string    `json:"digest"`
	Files       []string  `json:"files"`
	OperationId string    `json:"operation_id"`
}

// ValidatedEditPlan defines model for ValidatedEditPlan.
type ValidatedEditPlan struct {
	Edits        []FileEdit `json:"edits"`
	OperationId  string     `json:"operation_id"`
	SchemaDigest string     `json:"schema_digest"`
	Scope        string     `json:"scope"`
	SourceRefs   []string   `json:"source_refs"`
}

// WorkspaceSnapshot defines model for WorkspaceSnapshot.
type WorkspaceSnapshot struct {
	CapturedAt   time.Time         `json:"captured_at"`
	Links        []LinkReference   `json:"links"`
	PageDigests  map[string]string `json:"page_digests"`
	Pages        []PageSnapshot    `json:"pages"`
	SchemaDigest string            `json:"schema_digest"`
	Scope        string            `json:"scope"`
}

// OperationID defines model for OperationID.
type OperationID = string

// PageID defines model for PageID.
type PageID = string

// QueryString defines model for QueryString.
type QueryString = string

// JSONBodyBadRequest defines model for JSONBodyBadRequest.
type JSONBodyBadRequest = ErrorResponse

// NotFound defines model for NotFound.
type NotFound = ErrorResponse

// OperationFailed defines model for OperationFailed.
type OperationFailed = ErrorResponse

// OperationIDBadRequest defines model for OperationIDBadRequest.
type OperationIDBadRequest = ErrorResponse

// OperationNotApplyable defines model for OperationNotApplyable.
type OperationNotApplyable = ErrorResponse

// OperatorAuthorizationRequired defines model for OperatorAuthorizationRequired.
type OperatorAuthorizationRequired = ErrorResponse

// PageIDBadRequest defines model for PageIDBadRequest.
type PageIDBadRequest = ErrorResponse

// QueryStringBadRequest defines model for QueryStringBadRequest.
type QueryStringBadRequest = ErrorResponse

// ScopeOverrideForbidden defines model for ScopeOverrideForbidden.
type ScopeOverrideForbidden = ErrorResponse

// UnavailableError defines model for UnavailableError.
type UnavailableError = ErrorResponse

// QueryKnowledgeParams defines parameters for QueryKnowledge.
type QueryKnowledgeParams struct {
	// Q Non-empty query string.
	Q QueryString `form:"q" json:"q"`
}

// SearchPagesParams defines parameters for SearchPages.
type SearchPagesParams struct {
	// Q Non-empty query string.
	Q QueryString `form:"q" json:"q"`
}

// IngestSourceJSONRequestBody defines body for IngestSource for application/json ContentType.
type IngestSourceJSONRequestBody = SourceEnvelope

// PreviewSourceJSONRequestBody defines body for PreviewSource for application/json ContentType.
type PreviewSourceJSONRequestBody = SourceEnvelope

// FileQueryResultJSONRequestBody defines body for FileQueryResult for application/json ContentType.
type FileQueryResultJSONRequestBody = FilingRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Liveness probe alias
	// (GET /health)
	GetHealthAlias(w http.ResponseWriter, r *http.Request)
	// Readiness probe alias
	// (GET /health/ready)
	GetReadyAlias(w http.ResponseWriter, r *http.Request)
	// Liveness probe
	// (GET /healthz)
	GetHealth(w http.ResponseWriter, r *http.Request)
	// Readiness probe
	// (GET /readyz)
	GetReady(w http.ResponseWriter, r *http.Request)
	// Accept and process one immutable source revision
	// (POST /v1/ingest)
	IngestSource(w http.ResponseWriter, r *http.Request)
	// Accept and stage one immutable source revision
	// (POST /v1/ingest/preview)
	PreviewSource(w http.ResponseWriter, r *http.Request)
	// Run deterministic workspace lint
	// (GET /v1/lint)
	LintWorkspace(w http.ResponseWriter, r *http.Request)
	// Deterministic workspace lint alias
	// (GET /v1/lint-results)
	LintWorkspaceDashAlias(w http.ResponseWriter, r *http.Request)
	// Deterministic workspace lint alias
	// (GET /v1/lint/results)
	LintWorkspaceResultsAlias(w http.ResponseWriter, r *http.Request)
	// Read one durable operation status
	// (GET /v1/operations/{operation_id})
	GetOperation(w http.ResponseWriter, r *http.Request, operationId OperationID)
	// Apply one staged operation
	// (POST /v1/operations/{operation_id}/apply)
	ApplyOperation(w http.ResponseWriter, r *http.Request, operationId OperationID)
	// Read one durable operation status alias
	// (GET /v1/operations/{operation_id}/status)
	GetOperationStatusAlias(w http.ResponseWriter, r *http.Request, operationId OperationID)
	// Read one bounded canonical page
	// (GET /v1/pages/{page_id})
	GetPage(w http.ResponseWriter, r *http.Request, pageId PageID)
	// Read one bounded link neighborhood
	// (GET /v1/pages/{page_id}/links)
	GetPageLinks(w http.ResponseWriter, r *http.Request, pageId PageID)
	// Assemble bounded wiki references and citations
	// (GET /v1/query)
	QueryKnowledge(w http.ResponseWriter, r *http.Request, params QueryKnowledgeParams)
	// File a typed query result through the normal ingest gate
	// (POST /v1/query/file)
	FileQueryResult(w http.ResponseWriter, r *http.Request)
	// Search bounded page references
	// (GET /v1/search)
	SearchPages(w http.ResponseWriter, r *http.Request, params SearchPagesParams)
	// Read one durable operation status alias
	// (GET /v1/status/{operation_id})
	GetOperationLegacyStatusAlias(w http.ResponseWriter, r *http.Request, operationId OperationID)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetHealthAlias operation middleware
func (siw *ServerInterfaceWrapper) GetHealthAlias(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealthAlias(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetReadyAlias operation middleware
func (siw *ServerInterfaceWrapper) GetReadyAlias(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetReadyAlias(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetReady operation middleware
func (siw *ServerInterfaceWrapper) GetReady(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetReady(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// IngestSource operation middleware
func (siw *ServerInterfaceWrapper) IngestSource(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.IngestSource(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PreviewSource operation middleware
func (siw *ServerInterfaceWrapper) PreviewSource(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PreviewSource(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// LintWorkspace operation middleware
func (siw *ServerInterfaceWrapper) LintWorkspace(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.LintWorkspace(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// LintWorkspaceDashAlias operation middleware
func (siw *ServerInterfaceWrapper) LintWorkspaceDashAlias(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.LintWorkspaceDashAlias(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// LintWorkspaceResultsAlias operation middleware
func (siw *ServerInterfaceWrapper) LintWorkspaceResultsAlias(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.LintWorkspaceResultsAlias(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetOperation operation middleware
func (siw *ServerInterfaceWrapper) GetOperation(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "operation_id" -------------
	var operationId OperationID

	err = runtime.BindStyledParameterWithOptions("simple", "operation_id", r.PathValue("operation_id"), &operationId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "operation_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetOperation(w, r, operationId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ApplyOperation operation middleware
func (siw *ServerInterfaceWrapper) ApplyOperation(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "operation_id" -------------
	var operationId OperationID

	err = runtime.BindStyledParameterWithOptions("simple", "operation_id", r.PathValue("operation_id"), &operationId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "operation_id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ApplyOperation(w, r, operationId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetOperationStatusAlias operation middleware
func (siw *ServerInterfaceWrapper) GetOperationStatusAlias(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "operation_id" -------------
	var operationId OperationID

	err = runtime.BindStyledParameterWithOptions("simple", "operation_id", r.PathValue("operation_id"), &operationId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "operation_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetOperationStatusAlias(w, r, operationId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetPage operation middleware
func (siw *ServerInterfaceWrapper) GetPage(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "page_id" -------------
	var pageId PageID

	err = runtime.BindStyledParameterWithOptions("simple", "page_id", r.PathValue("page_id"), &pageId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetPage(w, r, pageId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetPageLinks operation middleware
func (siw *ServerInterfaceWrapper) GetPageLinks(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "page_id" -------------
	var pageId PageID

	err = runtime.BindStyledParameterWithOptions("simple", "page_id", r.PathValue("page_id"), &pageId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetPageLinks(w, r, pageId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// QueryKnowledge operation middleware
func (siw *ServerInterfaceWrapper) QueryKnowledge(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params QueryKnowledgeParams

	// ------------- Required query parameter "q" -------------

	if paramValue := r.URL.Query().Get("q"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "q"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "q", r.URL.Query(), &params.Q)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "q", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.QueryKnowledge(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// FileQueryResult operation middleware
func (siw *ServerInterfaceWrapper) FileQueryResult(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.FileQueryResult(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SearchPages operation middleware
func (siw *ServerInterfaceWrapper) SearchPages(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params SearchPagesParams

	// ------------- Required query parameter "q" -------------

	if paramValue := r.URL.Query().Get("q"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "q"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "q", r.URL.Query(), &params.Q)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "q", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SearchPages(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetOperationLegacyStatusAlias operation middleware
func (siw *ServerInterfaceWrapper) GetOperationLegacyStatusAlias(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "operation_id" -------------
	var operationId OperationID

	err = runtime.BindStyledParameterWithOptions("simple", "operation_id", r.PathValue("operation_id"), &operationId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "operation_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetOperationLegacyStatusAlias(w, r, operationId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("GET "+options.BaseURL+"/health", wrapper.GetHealthAlias)
	m.HandleFunc("GET "+options.BaseURL+"/health/ready", wrapper.GetReadyAlias)
	m.HandleFunc("GET "+options.BaseURL+"/healthz", wrapper.GetHealth)
	m.HandleFunc("GET "+options.BaseURL+"/readyz", wrapper.GetReady)
	m.HandleFunc("POST "+options.BaseURL+"/v1/ingest", wrapper.IngestSource)
	m.HandleFunc("POST "+options.BaseURL+"/v1/ingest/preview", wrapper.PreviewSource)
	m.HandleFunc("GET "+options.BaseURL+"/v1/lint", wrapper.LintWorkspace)
	m.HandleFunc("GET "+options.BaseURL+"/v1/lint-results", wrapper.LintWorkspaceDashAlias)
	m.HandleFunc("GET "+options.BaseURL+"/v1/lint/results", wrapper.LintWorkspaceResultsAlias)
	m.HandleFunc("GET "+options.BaseURL+"/v1/operations/{operation_id}", wrapper.GetOperation)
	m.HandleFunc("POST "+options.BaseURL+"/v1/operations/{operation_id}/apply", wrapper.ApplyOperation)
	m.HandleFunc("GET "+options.BaseURL+"/v1/operations/{operation_id}/status", wrapper.GetOperationStatusAlias)
	m.HandleFunc("GET "+options.BaseURL+"/v1/pages/{page_id}", wrapper.GetPage)
	m.HandleFunc("GET "+options.BaseURL+"/v1/pages/{page_id}/links", wrapper.GetPageLinks)
	m.HandleFunc("GET "+options.BaseURL+"/v1/query", wrapper.QueryKnowledge)
	m.HandleFunc("POST "+options.BaseURL+"/v1/query/file", wrapper.FileQueryResult)
	m.HandleFunc("GET "+options.BaseURL+"/v1/search", wrapper.SearchPages)
	m.HandleFunc("GET "+options.BaseURL+"/v1/status/{operation_id}", wrapper.GetOperationLegacyStatusAlias)

	return m
}

type JSONBodyBadRequestJSONResponse ErrorResponse

type NotFoundJSONResponse ErrorResponse

type OperationFailedJSONResponse ErrorResponse

type OperationIDBadRequestJSONResponse ErrorResponse

type OperationNotApplyableJSONResponse ErrorResponse

type OperatorAuthorizationRequiredJSONResponse ErrorResponse

type PageIDBadRequestJSONResponse ErrorResponse

type QueryStringBadRequestJSONResponse ErrorResponse

type ScopeOverrideForbiddenJSONResponse ErrorResponse

type UnavailableErrorJSONResponse ErrorResponse

type GetHealthAliasRequestObject struct {
}

type GetHealthAliasResponseObject interface {
	VisitGetHealthAliasResponse(w http.ResponseWriter) error
}

type GetHealthAlias200JSONResponse HealthResponse

func (response GetHealthAlias200JSONResponse) VisitGetHealthAliasResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetReadyAliasRequestObject struct {
}

type GetReadyAliasResponseObject interface {
	VisitGetReadyAliasResponse(w http.ResponseWriter) error
}

type GetReadyAlias200JSONResponse ReadyResponse

func (response GetReadyAlias200JSONResponse) VisitGetReadyAliasResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetReadyAlias503JSONResponse ReadyResponse

func (response GetReadyAlias503JSONResponse) VisitGetReadyAliasResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)

	return json.NewEncoder(w).Encode(response)
}

type GetHealthRequestObject struct {
}

type GetHealthResponseObject interface {
	VisitGetHealthResponse(w http.ResponseWriter) error
}

type GetHealth200JSONResponse HealthResponse

func (response GetHealth200JSONResponse) VisitGetHealthResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetReadyRequestObject struct {
}

type GetReadyResponseObject interface {
	VisitGetReadyResponse(w http.ResponseWriter) error
}

type GetReady200JSONResponse ReadyResponse

func (response GetReady200JSONResponse) VisitGetReadyResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetReady503JSONResponse ReadyResponse

func (response GetReady503JSONResponse) VisitGetReadyResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)

	return json.NewEncoder(w).Encode(response)
}

type IngestSourceRequestObject struct {
	Body *IngestSourceJSONRequestBody
}

type IngestSourceResponseObject interface {
	VisitIngestSourceResponse(w http.ResponseWriter) error
}

type IngestSource200JSONResponse IngestResult

func (response IngestSource200JSONResponse) VisitIngestSourceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type IngestSource400JSONResponse struct{ JSONBodyBadRequestJSONResponse }

func (response IngestSource400JSONResponse) VisitIngestSourceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type IngestSource401JSONResponse struct {
	OperatorAuthorizationRequiredJSONResponse
}

func (response IngestSource401JSONResponse) VisitIngestSourceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type IngestSource403JSONResponse struct {
	ScopeOverrideForbiddenJSONResponse
}

func (response IngestSource403JSONResponse) VisitIngestSourceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type IngestSource422JSONResponse struct{ OperationFailedJSONResponse }

func (response IngestSource422JSONResponse) VisitIngestSourceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(422)

	return json.NewEncoder(w).Encode(response)
}

type IngestSource503JSONResponse struct{ UnavailableErrorJSONResponse }

func (response IngestSource503JSONResponse) VisitIngestSourceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)

	return json.NewEncoder(w).Encode(response)
}

type PreviewSourceRequestObject struct {
	Body *PreviewSourceJSONRequestBody
}

type PreviewSourceResponseObject interface {
	VisitPreviewSourceResponse(w http.ResponseWriter) error
}

type PreviewSource200JSONResponse IngestResult

func (response PreviewSource200JSONResponse) VisitPreviewSourceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PreviewSource400JSONResponse struct{ JSONBodyBadRequestJSONResponse }

func (response PreviewSource400JSONResponse) VisitPreviewSourceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type PreviewSource401JSONResponse struct {
	OperatorAuthorizationRequiredJSONResponse
}

func (response PreviewSource401JSONResponse) VisitPreviewSourceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type PreviewSource403JSONResponse struct {
	ScopeOverrideForbiddenJSONResponse
}

func (response PreviewSource403JSONResponse) VisitPreviewSourceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type PreviewSource422JSONResponse struct{ OperationFailedJSONResponse }

func (response PreviewSource422JSONResponse) VisitPreviewSourceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(422)

	return json.NewEncoder(w).Encode(response)
}

type PreviewSource503JSONResponse struct{ UnavailableErrorJSONResponse }

func (response PreviewSource503JSONResponse) VisitPreviewSourceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)

	return json.NewEncoder(w).Encode(response)
}

type LintWorkspaceRequestObject struct {
}

type LintWorkspaceResponseObject interface {
	VisitLintWorkspaceResponse(w http.ResponseWriter) error
}

type LintWorkspace200JSONResponse LintReport

func (response LintWorkspace200JSONResponse) VisitLintWorkspaceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type LintWorkspace403JSONResponse struct {
	ScopeOverrideForbiddenJSONResponse
}

func (response LintWorkspace403JSONResponse) VisitLintWorkspaceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type LintWorkspace422JSONResponse struct{ OperationFailedJSONResponse }

func (response LintWorkspace422JSONResponse) VisitLintWorkspaceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(422)

	return json.NewEncoder(w).Encode(response)
}

type LintWorkspace503JSONResponse struct{ UnavailableErrorJSONResponse }

func (response LintWorkspace503JSONResponse) VisitLintWorkspaceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)

	return json.NewEncoder(w).Encode(response)
}

type LintWorkspaceDashAliasRequestObject struct {
}

type LintWorkspaceDashAliasResponseObject interface {
	VisitLintWorkspaceDashAliasResponse(w http.ResponseWriter) error
}

type LintWorkspaceDashAlias200JSONResponse LintReport

func (response LintWorkspaceDashAlias200JSONResponse) VisitLintWorkspaceDashAliasResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type LintWorkspaceDashAlias403JSONResponse struct {
	ScopeOverrideForbiddenJSONResponse
}

func (response LintWorkspaceDashAlias403JSONResponse) VisitLintWorkspaceDashAliasResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type LintWorkspaceDashAlias422JSONResponse struct{ OperationFailedJSONResponse }

func (response LintWorkspaceDashAlias422JSONResponse) VisitLintWorkspaceDashAliasResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(422)

	return json.NewEncoder(w).Encode(response)
}

type LintWorkspaceDashAlias503JSONResponse struct{ UnavailableErrorJSONResponse }

func (response LintWorkspaceDashAlias503JSONResponse) VisitLintWorkspaceDashAliasResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)

	return json.NewEncoder(w).Encode(response)
}

type LintWorkspaceResultsAliasRequestObject struct {
}

type LintWorkspaceResultsAliasResponseObject interface {
	VisitLintWorkspaceResultsAliasResponse(w http.ResponseWriter) error
}

type LintWorkspaceResultsAlias200JSONResponse LintReport

func (response LintWorkspaceResultsAlias200JSONResponse) VisitLintWorkspaceResultsAliasResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type LintWorkspaceResultsAlias403JSONResponse struct {
	ScopeOverrideForbiddenJSONResponse
}

func (response LintWorkspaceResultsAlias403JSONResponse) VisitLintWorkspaceResultsAliasResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type LintWorkspaceResultsAlias422JSONResponse struct{ OperationFailedJSONResponse }

func (response LintWorkspaceResultsAlias422JSONResponse) VisitLintWorkspaceResultsAliasResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(422)

	return json.NewEncoder(w).Encode(response)
}

type LintWorkspaceResultsAlias503JSONResponse struct{ UnavailableErrorJSONResponse }

func (response LintWorkspaceResultsAlias503JSONResponse) VisitLintWorkspaceResultsAliasResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)

	return json.NewEncoder(w).Encode(response)
}

type GetOperationRequestObject struct {
	OperationId OperationID `json:"operation_id"`
}

type GetOperationResponseObject interface {
	VisitGetOperationResponse(w http.ResponseWriter) error
}

type GetOperation200JSONResponse Operation

func (response GetOperation200JSONResponse) VisitGetOperationResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetOperation400JSONResponse struct {
	OperationIDBadRequestJSONResponse
}

func (response GetOperation400JSONResponse) VisitGetOperationResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type GetOperation403JSONResponse struct {
	ScopeOverrideForbiddenJSONResponse
}

func (response GetOperation403JSONResponse) VisitGetOperationResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type GetOperation404JSONResponse struct{ NotFoundJSONResponse }

func (response GetOperation404JSONResponse) VisitGetOperationResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetOperation422JSONResponse struct{ OperationFailedJSONResponse }

func (response GetOperation422JSONResponse) VisitGetOperationResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(422)

	return json.NewEncoder(w).Encode(response)
}

type GetOperation503JSONResponse struct{ UnavailableErrorJSONResponse }

func (response GetOperation503JSONResponse) VisitGetOperationResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)

	return json.NewEncoder(w).Encode(response)
}

type ApplyOperationRequestObject struct {
	OperationId OperationID `json:"operation_id"`
}

type ApplyOperationResponseObject interface {
	VisitApplyOperationResponse(w http.ResponseWriter) error
}

type ApplyOperation200JSONResponse ApplyResult

func (response ApplyOperation200JSONResponse) VisitApplyOperationResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ApplyOperation400JSONResponse struct {
	OperationIDBadRequestJSONResponse
}

func (response ApplyOperation400JSONResponse) VisitApplyOperationResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type ApplyOperation401JSONResponse struct {
	OperatorAuthorizationRequiredJSONResponse
}

func (response ApplyOperation401JSONResponse) VisitApplyOperationResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type ApplyOperation403JSONResponse struct {
	ScopeOverrideForbiddenJSONResponse
}

func (response ApplyOperation403JSONResponse) VisitApplyOperationResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type ApplyOperation404JSONResponse struct{ NotFoundJSONResponse }

func (response ApplyOperation404JSONResponse) VisitApplyOperationResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type ApplyOperation409JSONResponse struct {
	OperationNotApplyableJSONResponse
}

func (response ApplyOperation409JSONResponse) VisitApplyOperationResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type ApplyOperation422JSONResponse struct{ OperationFailedJSONResponse }

func (response ApplyOperation422JSONResponse) VisitApplyOperationResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(422)

	return json.NewEncoder(w).Encode(response)
}

type ApplyOperation503JSONResponse struct{ UnavailableErrorJSONResponse }

func (response ApplyOperation503JSONResponse) VisitApplyOperationResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)

	return json.NewEncoder(w).Encode(response)
}

type GetOperationStatusAliasRequestObject struct {
	OperationId OperationID `json:"operation_id"`
}

type GetOperationStatusAliasResponseObject interface {
	VisitGetOperationStatusAliasResponse(w http.ResponseWriter) error
}

type GetOperationStatusAlias200JSONResponse Operation

func (response GetOperationStatusAlias200JSONResponse) VisitGetOperationStatusAliasResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetOperationStatusAlias400JSONResponse struct {
	OperationIDBadRequestJSONResponse
}

func (response GetOperationStatusAlias400JSONResponse) VisitGetOperationStatusAliasResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type GetOperationStatusAlias403JSONResponse struct {
	ScopeOverrideForbiddenJSONResponse
}

func (response GetOperationStatusAlias403JSONResponse) VisitGetOperationStatusAliasResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type GetOperationStatusAlias404JSONResponse struct{ NotFoundJSONResponse }

func (response GetOperationStatusAlias404JSONResponse) VisitGetOperationStatusAliasResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetOperationStatusAlias422JSONResponse struct{ OperationFailedJSONResponse }

func (response GetOperationStatusAlias422JSONResponse) VisitGetOperationStatusAliasResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(422)

	return json.NewEncoder(w).Encode(response)
}

type GetOperationStatusAlias503JSONResponse struct{ UnavailableErrorJSONResponse }

func (response GetOperationStatusAlias503JSONResponse) VisitGetOperationStatusAliasResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)

	return json.NewEncoder(w).Encode(response)
}

type GetPageRequestObject struct {
	PageId PageID `json:"page_id"`
}

type GetPageResponseObject interface {
	VisitGetPageResponse(w http.ResponseWriter) error
}

type GetPage200JSONResponse PageSnapshot

func (response GetPage200JSONResponse) VisitGetPageResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetPage400JSONResponse struct{ PageIDBadRequestJSONResponse }

func (response GetPage400JSONResponse) VisitGetPageResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type GetPage403JSONResponse struct {
	ScopeOverrideForbiddenJSONResponse
}

func (response GetPage403JSONResponse) VisitGetPageResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type GetPage404JSONResponse struct{ NotFoundJSONResponse }

func (response GetPage404JSONResponse) VisitGetPageResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetPage422JSONResponse struct{ OperationFailedJSONResponse }

func (response GetPage422JSONResponse) VisitGetPageResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(422)

	return json.NewEncoder(w).Encode(response)
}

type GetPage503JSONResponse struct{ UnavailableErrorJSONResponse }

func (response GetPage503JSONResponse) VisitGetPageResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)

	return json.NewEncoder(w).Encode(response)
}

type GetPageLinksRequestObject struct {
	PageId PageID `json:"page_id"`
}

type GetPageLinksResponseObject interface {
	VisitGetPageLinksResponse(w http.ResponseWriter) error
}

type GetPageLinks200JSONResponse []LinkReference

func (response GetPageLinks200JSONResponse) VisitGetPageLinksResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetPageLinks400JSONResponse struct{ PageIDBadRequestJSONResponse }

func (response GetPageLinks400JSONResponse) VisitGetPageLinksResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type GetPageLinks403JSONResponse struct {
	ScopeOverrideForbiddenJSONResponse
}

func (response GetPageLinks403JSONResponse) VisitGetPageLinksResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type GetPageLinks404JSONResponse struct{ NotFoundJSONResponse }

func (response GetPageLinks404JSONResponse) VisitGetPageLinksResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetPageLinks422JSONResponse struct{ OperationFailedJSONResponse }

func (response GetPageLinks422JSONResponse) VisitGetPageLinksResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(422)

	return json.NewEncoder(w).Encode(response)
}

type GetPageLinks503JSONResponse struct{ UnavailableErrorJSONResponse }

func (response GetPageLinks503JSONResponse) VisitGetPageLinksResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)

	return json.NewEncoder(w).Encode(response)
}

type QueryKnowledgeRequestObject struct {
	Params QueryKnowledgeParams
}

type QueryKnowledgeResponseObject interface {
	VisitQueryKnowledgeResponse(w http.ResponseWriter) error
}

type QueryKnowledge200JSONResponse QueryResult

func (response QueryKnowledge200JSONResponse) VisitQueryKnowledgeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type QueryKnowledge400JSONResponse struct {
	QueryStringBadRequestJSONResponse
}

func (response QueryKnowledge400JSONResponse) VisitQueryKnowledgeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type QueryKnowledge403JSONResponse struct {
	ScopeOverrideForbiddenJSONResponse
}

func (response QueryKnowledge403JSONResponse) VisitQueryKnowledgeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type QueryKnowledge422JSONResponse struct{ OperationFailedJSONResponse }

func (response QueryKnowledge422JSONResponse) VisitQueryKnowledgeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(422)

	return json.NewEncoder(w).Encode(response)
}

type QueryKnowledge503JSONResponse struct{ UnavailableErrorJSONResponse }

func (response QueryKnowledge503JSONResponse) VisitQueryKnowledgeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)

	return json.NewEncoder(w).Encode(response)
}

type FileQueryResultRequestObject struct {
	Body *FileQueryResultJSONRequestBody
}

type FileQueryResultResponseObject interface {
	VisitFileQueryResultResponse(w http.ResponseWriter) error
}

type FileQueryResult200JSONResponse IngestResult

func (response FileQueryResult200JSONResponse) VisitFileQueryResultResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type FileQueryResult400JSONResponse struct{ JSONBodyBadRequestJSONResponse }

func (response FileQueryResult400JSONResponse) VisitFileQueryResultResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type FileQueryResult401JSONResponse struct {
	OperatorAuthorizationRequiredJSONResponse
}

func (response FileQueryResult401JSONResponse) VisitFileQueryResultResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type FileQueryResult403JSONResponse struct {
	ScopeOverrideForbiddenJSONResponse
}

func (response FileQueryResult403JSONResponse) VisitFileQueryResultResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type FileQueryResult422JSONResponse struct{ OperationFailedJSONResponse }

func (response FileQueryResult422JSONResponse) VisitFileQueryResultResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(422)

	return json.NewEncoder(w).Encode(response)
}

type FileQueryResult503JSONResponse struct{ UnavailableErrorJSONResponse }

func (response FileQueryResult503JSONResponse) VisitFileQueryResultResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)

	return json.NewEncoder(w).Encode(response)
}

type SearchPagesRequestObject struct {
	Params SearchPagesParams
}

type SearchPagesResponseObject interface {
	VisitSearchPagesResponse(w http.ResponseWriter) error
}

type SearchPages200JSONResponse []PageReference

func (response SearchPages200JSONResponse) VisitSearchPagesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type SearchPages400JSONResponse struct {
	QueryStringBadRequestJSONResponse
}

func (response SearchPages400JSONResponse) VisitSearchPagesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type SearchPages403JSONResponse struct {
	ScopeOverrideForbiddenJSONResponse
}

func (response SearchPages403JSONResponse) VisitSearchPagesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type SearchPages422JSONResponse struct{ OperationFailedJSONResponse }

func (response SearchPages422JSONResponse) VisitSearchPagesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(422)

	return json.NewEncoder(w).Encode(response)
}

type SearchPages503JSONResponse struct{ UnavailableErrorJSONResponse }

func (response SearchPages503JSONResponse) VisitSearchPagesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)

	return json.NewEncoder(w).Encode(response)
}

type GetOperationLegacyStatusAliasRequestObject struct {
	OperationId OperationID `json:"operation_id"`
}

type GetOperationLegacyStatusAliasResponseObject interface {
	VisitGetOperationLegacyStatusAliasResponse(w http.ResponseWriter) error
}

type GetOperationLegacyStatusAlias200JSONResponse Operation

func (response GetOperationLegacyStatusAlias200JSONResponse) VisitGetOperationLegacyStatusAliasResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetOperationLegacyStatusAlias400JSONResponse struct {
	OperationIDBadRequestJSONResponse
}

func (response GetOperationLegacyStatusAlias400JSONResponse) VisitGetOperationLegacyStatusAliasResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type GetOperationLegacyStatusAlias403JSONResponse struct {
	ScopeOverrideForbiddenJSONResponse
}

func (response GetOperationLegacyStatusAlias403JSONResponse) VisitGetOperationLegacyStatusAliasResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type GetOperationLegacyStatusAlias404JSONResponse struct{ NotFoundJSONResponse }

func (response GetOperationLegacyStatusAlias404JSONResponse) VisitGetOperationLegacyStatusAliasResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetOperationLegacyStatusAlias422JSONResponse struct{ OperationFailedJSONResponse }

func (response GetOperationLegacyStatusAlias422JSONResponse) VisitGetOperationLegacyStatusAliasResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(422)

	return json.NewEncoder(w).Encode(response)
}

type GetOperationLegacyStatusAlias503JSONResponse struct{ UnavailableErrorJSONResponse }

func (response GetOperationLegacyStatusAlias503JSONResponse) VisitGetOperationLegacyStatusAliasResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Liveness probe alias
	// (GET /health)
	GetHealthAlias(ctx context.Context, request GetHealthAliasRequestObject) (GetHealthAliasResponseObject, error)
	// Readiness probe alias
	// (GET /health/ready)
	GetReadyAlias(ctx context.Context, request GetReadyAliasRequestObject) (GetReadyAliasResponseObject, error)
	// Liveness probe
	// (GET /healthz)
	GetHealth(ctx context.Context, request GetHealthRequestObject) (GetHealthResponseObject, error)
	// Readiness probe
	// (GET /readyz)
	GetReady(ctx context.Context, request GetReadyRequestObject) (GetReadyResponseObject, error)
	// Accept and process one immutable source revision
	// (POST /v1/ingest)
	IngestSource(ctx context.Context, request IngestSourceRequestObject) (IngestSourceResponseObject, error)
	// Accept and stage one immutable source revision
	// (POST /v1/ingest/preview)
	PreviewSource(ctx context.Context, request PreviewSourceRequestObject) (PreviewSourceResponseObject, error)
	// Run deterministic workspace lint
	// (GET /v1/lint)
	LintWorkspace(ctx context.Context, request LintWorkspaceRequestObject) (LintWorkspaceResponseObject, error)
	// Deterministic workspace lint alias
	// (GET /v1/lint-results)
	LintWorkspaceDashAlias(ctx context.Context, request LintWorkspaceDashAliasRequestObject) (LintWorkspaceDashAliasResponseObject, error)
	// Deterministic workspace lint alias
	// (GET /v1/lint/results)
	LintWorkspaceResultsAlias(ctx context.Context, request LintWorkspaceResultsAliasRequestObject) (LintWorkspaceResultsAliasResponseObject, error)
	// Read one durable operation status
	// (GET /v1/operations/{operation_id})
	GetOperation(ctx context.Context, request GetOperationRequestObject) (GetOperationResponseObject, error)
	// Apply one staged operation
	// (POST /v1/operations/{operation_id}/apply)
	ApplyOperation(ctx context.Context, request ApplyOperationRequestObject) (ApplyOperationResponseObject, error)
	// Read one durable operation status alias
	// (GET /v1/operations/{operation_id}/status)
	GetOperationStatusAlias(ctx context.Context, request GetOperationStatusAliasRequestObject) (GetOperationStatusAliasResponseObject, error)
	// Read one bounded canonical page
	// (GET /v1/pages/{page_id})
	GetPage(ctx context.Context, request GetPageRequestObject) (GetPageResponseObject, error)
	// Read one bounded link neighborhood
	// (GET /v1/pages/{page_id}/links)
	GetPageLinks(ctx context.Context, request GetPageLinksRequestObject) (GetPageLinksResponseObject, error)
	// Assemble bounded wiki references and citations
	// (GET /v1/query)
	QueryKnowledge(ctx context.Context, request QueryKnowledgeRequestObject) (QueryKnowledgeResponseObject, error)
	// File a typed query result through the normal ingest gate
	// (POST /v1/query/file)
	FileQueryResult(ctx context.Context, request FileQueryResultRequestObject) (FileQueryResultResponseObject, error)
	// Search bounded page references
	// (GET /v1/search)
	SearchPages(ctx context.Context, request SearchPagesRequestObject) (SearchPagesResponseObject, error)
	// Read one durable operation status alias
	// (GET /v1/status/{operation_id})
	GetOperationLegacyStatusAlias(ctx context.Context, request GetOperationLegacyStatusAliasRequestObject) (GetOperationLegacyStatusAliasResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// GetHealthAlias operation middleware
func (sh *strictHandler) GetHealthAlias(w http.ResponseWriter, r *http.Request) {
	var request GetHealthAliasRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetHealthAlias(ctx, request.(GetHealthAliasRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetHealthAlias")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetHealthAliasResponseObject); ok {
		if err := validResponse.VisitGetHealthAliasResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetReadyAlias operation middleware
func (sh *strictHandler) GetReadyAlias(w http.ResponseWriter, r *http.Request) {
	var request GetReadyAliasRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetReadyAlias(ctx, request.(GetReadyAliasRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetReadyAlias")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetReadyAliasResponseObject); ok {
		if err := validResponse.VisitGetReadyAliasResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetHealth operation middleware
func (sh *strictHandler) GetHealth(w http.ResponseWriter, r *http.Request) {
	var request GetHealthRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetHealth(ctx, request.(GetHealthRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetHealth")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetHealthResponseObject); ok {
		if err := validResponse.VisitGetHealthResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetReady operation middleware
func (sh *strictHandler) GetReady(w http.ResponseWriter, r *http.Request) {
	var request GetReadyRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetReady(ctx, request.(GetReadyRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetReady")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetReadyResponseObject); ok {
		if err := validResponse.VisitGetReadyResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// IngestSource operation middleware
func (sh *strictHandler) IngestSource(w http.ResponseWriter, r *http.Request) {
	var request IngestSourceRequestObject

	var body IngestSourceJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.IngestSource(ctx, request.(IngestSourceRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "IngestSource")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(IngestSourceResponseObject); ok {
		if err := validResponse.VisitIngestSourceResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PreviewSource operation middleware
func (sh *strictHandler) PreviewSource(w http.ResponseWriter, r *http.Request) {
	var request PreviewSourceRequestObject

	var body PreviewSourceJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PreviewSource(ctx, request.(PreviewSourceRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PreviewSource")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PreviewSourceResponseObject); ok {
		if err := validResponse.VisitPreviewSourceResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// LintWorkspace operation middleware
func (sh *strictHandler) LintWorkspace(w http.ResponseWriter, r *http.Request) {
	var request LintWorkspaceRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.LintWorkspace(ctx, request.(LintWorkspaceRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "LintWorkspace")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(LintWorkspaceResponseObject); ok {
		if err := validResponse.VisitLintWorkspaceResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// LintWorkspaceDashAlias operation middleware
func (sh *strictHandler) LintWorkspaceDashAlias(w http.ResponseWriter, r *http.Request) {
	var request LintWorkspaceDashAliasRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.LintWorkspaceDashAlias(ctx, request.(LintWorkspaceDashAliasRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "LintWorkspaceDashAlias")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(LintWorkspaceDashAliasResponseObject); ok {
		if err := validResponse.VisitLintWorkspaceDashAliasResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// LintWorkspaceResultsAlias operation middleware
func (sh *strictHandler) LintWorkspaceResultsAlias(w http.ResponseWriter, r *http.Request) {
	var request LintWorkspaceResultsAliasRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.LintWorkspaceResultsAlias(ctx, request.(LintWorkspaceResultsAliasRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "LintWorkspaceResultsAlias")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(LintWorkspaceResultsAliasResponseObject); ok {
		if err := validResponse.VisitLintWorkspaceResultsAliasResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetOperation operation middleware
func (sh *strictHandler) GetOperation(w http.ResponseWriter, r *http.Request, operationId OperationID) {
	var request GetOperationRequestObject

	request.OperationId = operationId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetOperation(ctx, request.(GetOperationRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetOperation")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetOperationResponseObject); ok {
		if err := validResponse.VisitGetOperationResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ApplyOperation operation middleware
func (sh *strictHandler) ApplyOperation(w http.ResponseWriter, r *http.Request, operationId OperationID) {
	var request ApplyOperationRequestObject

	request.OperationId = operationId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ApplyOperation(ctx, request.(ApplyOperationRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ApplyOperation")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ApplyOperationResponseObject); ok {
		if err := validResponse.VisitApplyOperationResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetOperationStatusAlias operation middleware
func (sh *strictHandler) GetOperationStatusAlias(w http.ResponseWriter, r *http.Request, operationId OperationID) {
	var request GetOperationStatusAliasRequestObject

	request.OperationId = operationId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetOperationStatusAlias(ctx, request.(GetOperationStatusAliasRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetOperationStatusAlias")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetOperationStatusAliasResponseObject); ok {
		if err := validResponse.VisitGetOperationStatusAliasResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetPage operation middleware
func (sh *strictHandler) GetPage(w http.ResponseWriter, r *http.Request, pageId PageID) {
	var request GetPageRequestObject

	request.PageId = pageId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetPage(ctx, request.(GetPageRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetPage")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetPageResponseObject); ok {
		if err := validResponse.VisitGetPageResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetPageLinks operation middleware
func (sh *strictHandler) GetPageLinks(w http.ResponseWriter, r *http.Request, pageId PageID) {
	var request GetPageLinksRequestObject

	request.PageId = pageId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetPageLinks(ctx, request.(GetPageLinksRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetPageLinks")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetPageLinksResponseObject); ok {
		if err := validResponse.VisitGetPageLinksResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// QueryKnowledge operation middleware
func (sh *strictHandler) QueryKnowledge(w http.ResponseWriter, r *http.Request, params QueryKnowledgeParams) {
	var request QueryKnowledgeRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.QueryKnowledge(ctx, request.(QueryKnowledgeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "QueryKnowledge")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(QueryKnowledgeResponseObject); ok {
		if err := validResponse.VisitQueryKnowledgeResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// FileQueryResult operation middleware
func (sh *strictHandler) FileQueryResult(w http.ResponseWriter, r *http.Request) {
	var request FileQueryResultRequestObject

	var body FileQueryResultJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.FileQueryResult(ctx, request.(FileQueryResultRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "FileQueryResult")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(FileQueryResultResponseObject); ok {
		if err := validResponse.VisitFileQueryResultResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// SearchPages operation middleware
func (sh *strictHandler) SearchPages(w http.ResponseWriter, r *http.Request, params SearchPagesParams) {
	var request SearchPagesRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.SearchPages(ctx, request.(SearchPagesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "SearchPages")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(SearchPagesResponseObject); ok {
		if err := validResponse.VisitSearchPagesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetOperationLegacyStatusAlias operation middleware
func (sh *strictHandler) GetOperationLegacyStatusAlias(w http.ResponseWriter, r *http.Request, operationId OperationID) {
	var request GetOperationLegacyStatusAliasRequestObject

	request.OperationId = operationId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetOperationLegacyStatusAlias(ctx, request.(GetOperationLegacyStatusAliasRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetOperationLegacyStatusAlias")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetOperationLegacyStatusAliasResponseObject); ok {
		if err := validResponse.VisitGetOperationLegacyStatusAliasResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}
