//go:build go1.22

// Package operatorapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package operatorapi

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"

	domain "github.com/baldaworks/knowl/pkg/knowl/types"
	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
)

const (
	OperatorBearerScopes = "OperatorBearer.Scopes"
)

// DocumentList defines model for DocumentList.
type DocumentList = domain.OperatorList[domain.OperatorDocumentSummary]

// Error defines model for Error.
type Error struct {
	Error string `json:"error"`
}

// MaintenanceCounts defines model for MaintenanceCounts.
type MaintenanceCounts = domain.MaintenanceCounts

// OperationList defines model for OperationList.
type OperationList = domain.OperatorList[domain.OperatorOperationSummary]

// OperatorCatalog defines model for OperatorCatalog.
type OperatorCatalog = domain.OperatorCatalog

// OperatorCatalogChild defines model for OperatorCatalogChild.
type OperatorCatalogChild = domain.OperatorCatalogChild

// OperatorCatalogSummary defines model for OperatorCatalogSummary.
type OperatorCatalogSummary = domain.OperatorCatalogSummary

// OperatorDocumentSummary defines model for OperatorDocumentSummary.
type OperatorDocumentSummary = domain.OperatorDocumentSummary

// OperatorOperationSummary defines model for OperatorOperationSummary.
type OperatorOperationSummary = domain.OperatorOperationSummary

// OperatorPage defines model for OperatorPage.
type OperatorPage = domain.OperatorPage

// OperatorPageMetadata defines model for OperatorPageMetadata.
type OperatorPageMetadata = domain.OperatorPageMetadata

// OperatorPageSource defines model for OperatorPageSource.
type OperatorPageSource = domain.OperatorPageSource

// OperatorPageSummary defines model for OperatorPageSummary.
type OperatorPageSummary = domain.OperatorPageSummary

// OperatorSourceDetail defines model for OperatorSourceDetail.
type OperatorSourceDetail = domain.OperatorSourceDetail

// OperatorSourceRevision defines model for OperatorSourceRevision.
type OperatorSourceRevision = domain.OperatorSourceRevision

// OperatorSourceStatus defines model for OperatorSourceStatus.
type OperatorSourceStatus = domain.OperatorSourceStatus

// OperatorSourceSummary defines model for OperatorSourceSummary.
type OperatorSourceSummary = domain.OperatorSourceSummary

// PageList defines model for PageList.
type PageList = domain.OperatorList[domain.OperatorPageSummary]

// SourceList defines model for SourceList.
type SourceList = domain.OperatorList[domain.OperatorSourceSummary]

// SourceRef defines model for SourceRef.
type SourceRef = domain.SourceRef

// SourceVersion defines model for SourceVersion.
type SourceVersion = domain.SourceVersion

// SyncCounts defines model for SyncCounts.
type SyncCounts = domain.SyncCounts

// Cursor defines model for Cursor.
type Cursor = string

// Limit defines model for Limit.
type Limit = int

// GetCatalogsParams defines parameters for GetCatalogs.
type GetCatalogsParams struct {
	ParentId *string `form:"parent_id,omitempty" json:"parent_id,omitempty"`
	Limit    *Limit  `form:"limit,omitempty" json:"limit,omitempty"`

	// Cursor Signed process-local cursor; restart invalidates it with cursor_invalid. Bound to endpoint, scope, filters, limit and canonical snapshot where applicable.
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`
}

// GetOperationsParams defines parameters for GetOperations.
type GetOperationsParams struct {
	Status   *string `form:"status,omitempty" json:"status,omitempty"`
	SourceId *string `form:"source_id,omitempty" json:"source_id,omitempty"`
	Limit    *Limit  `form:"limit,omitempty" json:"limit,omitempty"`

	// Cursor Signed process-local cursor; restart invalidates it with cursor_invalid. Bound to endpoint, scope, filters, limit and canonical snapshot where applicable.
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`
}

// GetPageParams defines parameters for GetPage.
type GetPageParams struct {
	PageId string `form:"page_id" json:"page_id"`
}

// GetPagesParams defines parameters for GetPages.
type GetPagesParams struct {
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`

	// Cursor Signed process-local cursor; restart invalidates it with cursor_invalid. Bound to endpoint, scope, filters, limit and canonical snapshot where applicable.
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`
}

// GetSourceRevisionParams defines parameters for GetSourceRevision.
type GetSourceRevisionParams struct {
	SourceRef string `form:"source_ref" json:"source_ref"`
}

// GetSourcesParams defines parameters for GetSources.
type GetSourcesParams struct {
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`

	// Cursor Signed process-local cursor; restart invalidates it with cursor_invalid. Bound to endpoint, scope, filters, limit and canonical snapshot where applicable.
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`
}

// GetSourceParams defines parameters for GetSource.
type GetSourceParams struct {
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`

	// Cursor Signed process-local cursor; restart invalidates it with cursor_invalid. Bound to endpoint, scope, filters, limit and canonical snapshot where applicable.
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`
}

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /operator/v1/catalogs)
	GetCatalogs(w http.ResponseWriter, r *http.Request, params GetCatalogsParams)

	// (GET /operator/v1/operations)
	GetOperations(w http.ResponseWriter, r *http.Request, params GetOperationsParams)

	// (GET /operator/v1/page)
	GetPage(w http.ResponseWriter, r *http.Request, params GetPageParams)

	// (GET /operator/v1/pages)
	GetPages(w http.ResponseWriter, r *http.Request, params GetPagesParams)

	// (GET /operator/v1/source-revision)
	GetSourceRevision(w http.ResponseWriter, r *http.Request, params GetSourceRevisionParams)

	// (GET /operator/v1/sources)
	GetSources(w http.ResponseWriter, r *http.Request, params GetSourcesParams)

	// (GET /operator/v1/sources/{source_id})
	GetSource(w http.ResponseWriter, r *http.Request, sourceId string, params GetSourceParams)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetCatalogs operation middleware
func (siw *ServerInterfaceWrapper) GetCatalogs(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, OperatorBearerScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params GetCatalogsParams

	// ------------- Optional query parameter "parent_id" -------------

	err = runtime.BindQueryParameter("form", true, false, "parent_id", r.URL.Query(), &params.ParentId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "parent_id", Err: err})
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameter("form", true, false, "cursor", r.URL.Query(), &params.Cursor)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cursor", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCatalogs(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetOperations operation middleware
func (siw *ServerInterfaceWrapper) GetOperations(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, OperatorBearerScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params GetOperationsParams

	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameter("form", true, false, "status", r.URL.Query(), &params.Status)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "status", Err: err})
		return
	}

	// ------------- Optional query parameter "source_id" -------------

	err = runtime.BindQueryParameter("form", true, false, "source_id", r.URL.Query(), &params.SourceId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "source_id", Err: err})
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameter("form", true, false, "cursor", r.URL.Query(), &params.Cursor)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cursor", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetOperations(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetPage operation middleware
func (siw *ServerInterfaceWrapper) GetPage(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, OperatorBearerScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params GetPageParams

	// ------------- Required query parameter "page_id" -------------

	if paramValue := r.URL.Query().Get("page_id"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "page_id"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "page_id", r.URL.Query(), &params.PageId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetPage(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetPages operation middleware
func (siw *ServerInterfaceWrapper) GetPages(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, OperatorBearerScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params GetPagesParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameter("form", true, false, "cursor", r.URL.Query(), &params.Cursor)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cursor", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetPages(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetSourceRevision operation middleware
func (siw *ServerInterfaceWrapper) GetSourceRevision(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, OperatorBearerScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params GetSourceRevisionParams

	// ------------- Required query parameter "source_ref" -------------

	if paramValue := r.URL.Query().Get("source_ref"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "source_ref"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "source_ref", r.URL.Query(), &params.SourceRef)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "source_ref", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetSourceRevision(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetSources operation middleware
func (siw *ServerInterfaceWrapper) GetSources(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, OperatorBearerScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params GetSourcesParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameter("form", true, false, "cursor", r.URL.Query(), &params.Cursor)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cursor", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetSources(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetSource operation middleware
func (siw *ServerInterfaceWrapper) GetSource(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "source_id" -------------
	var sourceId string

	err = runtime.BindStyledParameterWithOptions("simple", "source_id", r.PathValue("source_id"), &sourceId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "source_id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, OperatorBearerScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params GetSourceParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameter("form", true, false, "cursor", r.URL.Query(), &params.Cursor)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cursor", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetSource(w, r, sourceId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("GET "+options.BaseURL+"/operator/v1/catalogs", wrapper.GetCatalogs)
	m.HandleFunc("GET "+options.BaseURL+"/operator/v1/operations", wrapper.GetOperations)
	m.HandleFunc("GET "+options.BaseURL+"/operator/v1/page", wrapper.GetPage)
	m.HandleFunc("GET "+options.BaseURL+"/operator/v1/pages", wrapper.GetPages)
	m.HandleFunc("GET "+options.BaseURL+"/operator/v1/source-revision", wrapper.GetSourceRevision)
	m.HandleFunc("GET "+options.BaseURL+"/operator/v1/sources", wrapper.GetSources)
	m.HandleFunc("GET "+options.BaseURL+"/operator/v1/sources/{source_id}", wrapper.GetSource)

	return m
}

type GetCatalogsRequestObject struct {
	Params GetCatalogsParams
}

type GetCatalogsResponseObject interface {
	VisitGetCatalogsResponse(w http.ResponseWriter) error
}

type GetCatalogs200JSONResponse OperatorCatalog

func (response GetCatalogs200JSONResponse) VisitGetCatalogsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetCatalogs400JSONResponse Error

func (response GetCatalogs400JSONResponse) VisitGetCatalogsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type GetCatalogs401JSONResponse Error

func (response GetCatalogs401JSONResponse) VisitGetCatalogsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type GetCatalogs403JSONResponse Error

func (response GetCatalogs403JSONResponse) VisitGetCatalogsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type GetCatalogs404JSONResponse Error

func (response GetCatalogs404JSONResponse) VisitGetCatalogsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetCatalogs409JSONResponse Error

func (response GetCatalogs409JSONResponse) VisitGetCatalogsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type GetCatalogs413JSONResponse Error

func (response GetCatalogs413JSONResponse) VisitGetCatalogsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(413)

	return json.NewEncoder(w).Encode(response)
}

type GetCatalogs415JSONResponse Error

func (response GetCatalogs415JSONResponse) VisitGetCatalogsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(415)

	return json.NewEncoder(w).Encode(response)
}

type GetCatalogs500JSONResponse Error

func (response GetCatalogs500JSONResponse) VisitGetCatalogsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetCatalogs503JSONResponse Error

func (response GetCatalogs503JSONResponse) VisitGetCatalogsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)

	return json.NewEncoder(w).Encode(response)
}

type GetOperationsRequestObject struct {
	Params GetOperationsParams
}

type GetOperationsResponseObject interface {
	VisitGetOperationsResponse(w http.ResponseWriter) error
}

type GetOperations200JSONResponse OperationList

func (response GetOperations200JSONResponse) VisitGetOperationsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetOperations400JSONResponse Error

func (response GetOperations400JSONResponse) VisitGetOperationsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type GetOperations401JSONResponse Error

func (response GetOperations401JSONResponse) VisitGetOperationsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type GetOperations403JSONResponse Error

func (response GetOperations403JSONResponse) VisitGetOperationsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type GetOperations404JSONResponse Error

func (response GetOperations404JSONResponse) VisitGetOperationsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetOperations409JSONResponse Error

func (response GetOperations409JSONResponse) VisitGetOperationsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type GetOperations413JSONResponse Error

func (response GetOperations413JSONResponse) VisitGetOperationsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(413)

	return json.NewEncoder(w).Encode(response)
}

type GetOperations415JSONResponse Error

func (response GetOperations415JSONResponse) VisitGetOperationsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(415)

	return json.NewEncoder(w).Encode(response)
}

type GetOperations500JSONResponse Error

func (response GetOperations500JSONResponse) VisitGetOperationsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetOperations503JSONResponse Error

func (response GetOperations503JSONResponse) VisitGetOperationsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)

	return json.NewEncoder(w).Encode(response)
}

type GetPageRequestObject struct {
	Params GetPageParams
}

type GetPageResponseObject interface {
	VisitGetPageResponse(w http.ResponseWriter) error
}

type GetPage200JSONResponse OperatorPage

func (response GetPage200JSONResponse) VisitGetPageResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetPage400JSONResponse Error

func (response GetPage400JSONResponse) VisitGetPageResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type GetPage401JSONResponse Error

func (response GetPage401JSONResponse) VisitGetPageResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type GetPage403JSONResponse Error

func (response GetPage403JSONResponse) VisitGetPageResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type GetPage404JSONResponse Error

func (response GetPage404JSONResponse) VisitGetPageResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetPage409JSONResponse Error

func (response GetPage409JSONResponse) VisitGetPageResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type GetPage413JSONResponse Error

func (response GetPage413JSONResponse) VisitGetPageResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(413)

	return json.NewEncoder(w).Encode(response)
}

type GetPage415JSONResponse Error

func (response GetPage415JSONResponse) VisitGetPageResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(415)

	return json.NewEncoder(w).Encode(response)
}

type GetPage500JSONResponse Error

func (response GetPage500JSONResponse) VisitGetPageResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetPage503JSONResponse Error

func (response GetPage503JSONResponse) VisitGetPageResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)

	return json.NewEncoder(w).Encode(response)
}

type GetPagesRequestObject struct {
	Params GetPagesParams
}

type GetPagesResponseObject interface {
	VisitGetPagesResponse(w http.ResponseWriter) error
}

type GetPages200JSONResponse PageList

func (response GetPages200JSONResponse) VisitGetPagesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetPages400JSONResponse Error

func (response GetPages400JSONResponse) VisitGetPagesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type GetPages401JSONResponse Error

func (response GetPages401JSONResponse) VisitGetPagesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type GetPages403JSONResponse Error

func (response GetPages403JSONResponse) VisitGetPagesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type GetPages404JSONResponse Error

func (response GetPages404JSONResponse) VisitGetPagesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetPages409JSONResponse Error

func (response GetPages409JSONResponse) VisitGetPagesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type GetPages413JSONResponse Error

func (response GetPages413JSONResponse) VisitGetPagesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(413)

	return json.NewEncoder(w).Encode(response)
}

type GetPages415JSONResponse Error

func (response GetPages415JSONResponse) VisitGetPagesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(415)

	return json.NewEncoder(w).Encode(response)
}

type GetPages500JSONResponse Error

func (response GetPages500JSONResponse) VisitGetPagesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetPages503JSONResponse Error

func (response GetPages503JSONResponse) VisitGetPagesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)

	return json.NewEncoder(w).Encode(response)
}

type GetSourceRevisionRequestObject struct {
	Params GetSourceRevisionParams
}

type GetSourceRevisionResponseObject interface {
	VisitGetSourceRevisionResponse(w http.ResponseWriter) error
}

type GetSourceRevision200JSONResponse OperatorSourceRevision

func (response GetSourceRevision200JSONResponse) VisitGetSourceRevisionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetSourceRevision400JSONResponse Error

func (response GetSourceRevision400JSONResponse) VisitGetSourceRevisionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type GetSourceRevision401JSONResponse Error

func (response GetSourceRevision401JSONResponse) VisitGetSourceRevisionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type GetSourceRevision403JSONResponse Error

func (response GetSourceRevision403JSONResponse) VisitGetSourceRevisionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type GetSourceRevision404JSONResponse Error

func (response GetSourceRevision404JSONResponse) VisitGetSourceRevisionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetSourceRevision409JSONResponse Error

func (response GetSourceRevision409JSONResponse) VisitGetSourceRevisionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type GetSourceRevision413JSONResponse Error

func (response GetSourceRevision413JSONResponse) VisitGetSourceRevisionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(413)

	return json.NewEncoder(w).Encode(response)
}

type GetSourceRevision415JSONResponse Error

func (response GetSourceRevision415JSONResponse) VisitGetSourceRevisionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(415)

	return json.NewEncoder(w).Encode(response)
}

type GetSourceRevision500JSONResponse Error

func (response GetSourceRevision500JSONResponse) VisitGetSourceRevisionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetSourceRevision503JSONResponse Error

func (response GetSourceRevision503JSONResponse) VisitGetSourceRevisionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)

	return json.NewEncoder(w).Encode(response)
}

type GetSourcesRequestObject struct {
	Params GetSourcesParams
}

type GetSourcesResponseObject interface {
	VisitGetSourcesResponse(w http.ResponseWriter) error
}

type GetSources200JSONResponse SourceList

func (response GetSources200JSONResponse) VisitGetSourcesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetSources400JSONResponse Error

func (response GetSources400JSONResponse) VisitGetSourcesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type GetSources401JSONResponse Error

func (response GetSources401JSONResponse) VisitGetSourcesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type GetSources403JSONResponse Error

func (response GetSources403JSONResponse) VisitGetSourcesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type GetSources404JSONResponse Error

func (response GetSources404JSONResponse) VisitGetSourcesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetSources409JSONResponse Error

func (response GetSources409JSONResponse) VisitGetSourcesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type GetSources413JSONResponse Error

func (response GetSources413JSONResponse) VisitGetSourcesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(413)

	return json.NewEncoder(w).Encode(response)
}

type GetSources415JSONResponse Error

func (response GetSources415JSONResponse) VisitGetSourcesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(415)

	return json.NewEncoder(w).Encode(response)
}

type GetSources500JSONResponse Error

func (response GetSources500JSONResponse) VisitGetSourcesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetSources503JSONResponse Error

func (response GetSources503JSONResponse) VisitGetSourcesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)

	return json.NewEncoder(w).Encode(response)
}

type GetSourceRequestObject struct {
	SourceId string `json:"source_id"`
	Params   GetSourceParams
}

type GetSourceResponseObject interface {
	VisitGetSourceResponse(w http.ResponseWriter) error
}

type GetSource200JSONResponse OperatorSourceDetail

func (response GetSource200JSONResponse) VisitGetSourceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetSource400JSONResponse Error

func (response GetSource400JSONResponse) VisitGetSourceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type GetSource401JSONResponse Error

func (response GetSource401JSONResponse) VisitGetSourceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type GetSource403JSONResponse Error

func (response GetSource403JSONResponse) VisitGetSourceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type GetSource404JSONResponse Error

func (response GetSource404JSONResponse) VisitGetSourceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetSource409JSONResponse Error

func (response GetSource409JSONResponse) VisitGetSourceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type GetSource413JSONResponse Error

func (response GetSource413JSONResponse) VisitGetSourceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(413)

	return json.NewEncoder(w).Encode(response)
}

type GetSource415JSONResponse Error

func (response GetSource415JSONResponse) VisitGetSourceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(415)

	return json.NewEncoder(w).Encode(response)
}

type GetSource500JSONResponse Error

func (response GetSource500JSONResponse) VisitGetSourceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetSource503JSONResponse Error

func (response GetSource503JSONResponse) VisitGetSourceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {

	// (GET /operator/v1/catalogs)
	GetCatalogs(ctx context.Context, request GetCatalogsRequestObject) (GetCatalogsResponseObject, error)

	// (GET /operator/v1/operations)
	GetOperations(ctx context.Context, request GetOperationsRequestObject) (GetOperationsResponseObject, error)

	// (GET /operator/v1/page)
	GetPage(ctx context.Context, request GetPageRequestObject) (GetPageResponseObject, error)

	// (GET /operator/v1/pages)
	GetPages(ctx context.Context, request GetPagesRequestObject) (GetPagesResponseObject, error)

	// (GET /operator/v1/source-revision)
	GetSourceRevision(ctx context.Context, request GetSourceRevisionRequestObject) (GetSourceRevisionResponseObject, error)

	// (GET /operator/v1/sources)
	GetSources(ctx context.Context, request GetSourcesRequestObject) (GetSourcesResponseObject, error)

	// (GET /operator/v1/sources/{source_id})
	GetSource(ctx context.Context, request GetSourceRequestObject) (GetSourceResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// GetCatalogs operation middleware
func (sh *strictHandler) GetCatalogs(w http.ResponseWriter, r *http.Request, params GetCatalogsParams) {
	var request GetCatalogsRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetCatalogs(ctx, request.(GetCatalogsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetCatalogs")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetCatalogsResponseObject); ok {
		if err := validResponse.VisitGetCatalogsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetOperations operation middleware
func (sh *strictHandler) GetOperations(w http.ResponseWriter, r *http.Request, params GetOperationsParams) {
	var request GetOperationsRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetOperations(ctx, request.(GetOperationsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetOperations")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetOperationsResponseObject); ok {
		if err := validResponse.VisitGetOperationsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetPage operation middleware
func (sh *strictHandler) GetPage(w http.ResponseWriter, r *http.Request, params GetPageParams) {
	var request GetPageRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetPage(ctx, request.(GetPageRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetPage")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetPageResponseObject); ok {
		if err := validResponse.VisitGetPageResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetPages operation middleware
func (sh *strictHandler) GetPages(w http.ResponseWriter, r *http.Request, params GetPagesParams) {
	var request GetPagesRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetPages(ctx, request.(GetPagesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetPages")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetPagesResponseObject); ok {
		if err := validResponse.VisitGetPagesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetSourceRevision operation middleware
func (sh *strictHandler) GetSourceRevision(w http.ResponseWriter, r *http.Request, params GetSourceRevisionParams) {
	var request GetSourceRevisionRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetSourceRevision(ctx, request.(GetSourceRevisionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetSourceRevision")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetSourceRevisionResponseObject); ok {
		if err := validResponse.VisitGetSourceRevisionResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetSources operation middleware
func (sh *strictHandler) GetSources(w http.ResponseWriter, r *http.Request, params GetSourcesParams) {
	var request GetSourcesRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetSources(ctx, request.(GetSourcesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetSources")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetSourcesResponseObject); ok {
		if err := validResponse.VisitGetSourcesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetSource operation middleware
func (sh *strictHandler) GetSource(w http.ResponseWriter, r *http.Request, sourceId string, params GetSourceParams) {
	var request GetSourceRequestObject

	request.SourceId = sourceId
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetSource(ctx, request.(GetSourceRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetSource")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetSourceResponseObject); ok {
		if err := validResponse.VisitGetSourceResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}
